### ISSUE TITLE
Should we change "method =" to "unit =" in unnest_tokens

### ISSUE THREAD

**Issue by dgrtwo** [juliasilge/tidytext#1]
In unnest_tokens, we have method = "words", "sentences", etc. But really this should describe the unit we are tokenizing on. Maybe unit =, or something similar, is a better argument name?

(Sorry this was posted early, keyboard mishap)

**Comment by juliasilge** [comment]
Eeeeeeh, this is tough. Neither of those is perfect, but I could be swayed either way. I am happy to switch to "unit = " if you think that is clearer.

What it really is, I think, is "token = " but of course that is what we are calling the result of the process. Would it be super lame to use token = "words", "sentences", ... and then the parameters in and out are input_col and output_col or something like that?

**Comment by dgrtwo** [comment]
I think you are right! I have been second-guessing the "token" and "text" argument names, so I think output, input, and then token = is the right choice!

**Comment by juliasilge** [comment]
OK! I will do this tomorrow or Thursday.
