### ISSUE TITLE
error with russian text in ngram tokenisation

### ISSUE THREAD

**Issue by panchenkoai** [juliasilge/tidytext#104]
Hi, have some problem with tokenisaion on russian text.
If I tokenise by word it's  ok, but when I tokenise by ngramm n =2 or bigger  n encoding of my text is fail. Please help.
Before tokenise text I implemented enc2utf8 to string collumn.

`x_1 <- '5882898'`
`x_2 <- enc2utf8("увеличить ассортимент и снизить цены")`

`content_x <- data_frame(x_1=x_1,x_2=x_2)`
#by word
`t1 <- content_x%>% 
  select("x_1","x_2")%>%
  unnest_tokens(word, x_2)#ok`

#result
5882898 | увеличить
5882898 | ассортимент
5882898 | и
5882898 | снизить
5882898 | цены
#by ngramm-----------------
`t2 <- content_x%>% 
  select("x_1","x_2")%>%
  unnest_tokens(bigram, x_2,token = "ngrams",n=2)#error`

#result
5882898 | сѓрірµр»рёс‡рёс‚сњ р°сѓсѓрѕсђс‚рёрјрµрѕс‚
5882898 | р°сѓсѓрѕсђс‚рёрјрµрѕс‚ рё
5882898 | рё   сѓрѕрёр·рёс‚сњ
5882898 | сѓрѕрёр·рёс‚сњ с†рµрѕс‹

**Comment by juliasilge** [comment]
Hello there, @andreypanchenko! Thanks for your interest in tidytext. Unfortunately, this is a Windows-specific, low-level problem with R that is not related to tidytext. Other users have run into this same problem with Estonian in #80 and Polish in #63. You can see here the results I get locally using OSX.

``` r
library(tidyverse)
library(tidytext)

x_1 <- '5882898'
x_2 <- enc2utf8("увеличить ассортимент и снизить цены")

content_x <- data_frame(x_1 = x_1,
                        x_2 = x_2)

t2 <- content_x %>% 
  unnest_tokens(bigram, x_2, token = "ngrams", n=2)

t2
#> # A tibble: 4 x 2
#>   x_1     bigram               
#>   <chr>   <chr>                
#> 1 5882898 увеличить ассортимент
#> 2 5882898 ассортимент и        
#> 3 5882898 и снизить            
#> 4 5882898 снизить цены
```

Created on 2018-03-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Unfortunately, we can't change anything in the code here in tidytext to make this problem better or worse. I know that is frustrating! Other people involved in the R text world like @patperry have said they suspect this is a problem with R encoding itself on Windows, not anything in any of the packages. Check out some of the other issues to see how things have progressed.

**Comment by patperry** [comment]
I don't know the specifics of what's going wrong here, but for what it's with, I can reproduce your problem on Windows. If you need a quick fix, `corpus::term_counts(x_2, ngrams = 2)` gives the correct output.

Internally, the `corpus` package uses `utf8::as_utf8` to convert input text to UTF-8. This works around a low-level bug in Windows R, probably the one you're running into. The R developers have fixed this bug in R-devel.

**Comment by patperry** [comment]
I just remembered that this is a bug in `tokenizers`, not in R. I reported the bug and told them how to fix it: https://github.com/ropensci/tokenizers/issues/58

**Comment by juliasilge** [comment]
Ah, thank you, @patperry! 🙌
