### ISSUE TITLE
tidiers for stm::estimateEffect class

### ISSUE THREAD

**Issue by chapmandu2** [juliasilge/tidytext#107]
Would be great to be able to tidy output from the estimateEffect class in stm as well as the topic models themselves.

**Comment by juliasilge** [comment]
This is a great idea, and something I have been wanting to do. 🙌

It will be a few weeks before I work on this.

**Comment by chapmandu2** [comment]
Sounds great.  Thanks for the awesome package and blog, has been really helpful for a project I'm working on!  I would have been waiting hours for LDA to run had you not put me onto stm, with the added bonus that it handles covariates...  I might end up writing something myself in which case I'll fork/PR.  Thanks again!

**Comment by jefferickson** [comment]
@juliasilge @chapmandu2 I have created a PR to tidy output from `estimateEffect`: https://github.com/juliasilge/tidytext/pull/115. I hope this is helpful!

**Comment by juliasilge** [comment]
This PR is now merged and is available in the dev version here on GitHub. Thanks so much to @jefferickson for his work here! ✨
