### ISSUE TITLE
Cast to dfm with metadata for stm?

### ISSUE THREAD

**Issue by mfherman** [juliasilge/tidytext#114]
Thanks for the wonderful package! I've been using tidytext to preprocess text that I want to model using the stm package. As you note in your [blog post](https://juliasilge.com/blog/sherlock-holmes-stm/), stm can take a dfm object as input and it's very easy to convert from tidy text format to dfm using `cast_dfm()`.

But I'm wondering, what is the best way to go from a tidy text format with document-level metadata to a dfm object with metadata? For now, I've been doing something like this where I create the dfm object and then update the docvars slot of the dfm object with the metadata:

```
text_dfm <- tidy_text %>%
    count(doc_id, word) %>%
    arrange(doc_id) %>%
    cast_dfm(doc_id, word, n)

text_dfm@docvars <- tidy_text %>%
  arrange(doc_id, meta1, meta2, meta3)
```
This feels a little fragile as it relies on the metadata data frame being in the same order as the dfm. Is there a better way to do this?

Thanks again!

**Comment by juliasilge** [comment]
Thank you so much for your interest in tidytext! 

I find I am having a much better experience avoiding using any quanteda objects and just going straight to plain old sparse matrices when I use stm. I should blog more about this with some workflows, but here is an example.

``` r
library(tidyverse)
library(tidytext)
library(stm)
library(janeaustenr)

tidy_austen <- austen_books() %>%
    mutate(line = row_number()) %>%
    unnest_tokens(word, text) %>%
    anti_join(stop_words)
#> Joining, by = "word"

austen_sparse <- tidy_austen %>%
    count(line, word) %>%
    cast_sparse(line, word, n)

## notice that I am scrambling the order of the rows
## the covariate data is in random order now
covariates <- tidy_austen %>%
    sample_frac() %>%
    distinct(line, book)

topic_model <- stm(austen_sparse, 
                   K = 12, 
                   prevalence = ~ book,
                   data = covariates,
                   verbose = FALSE, 
                   init.type = "Spectral")

topic_model
#> A topic model with 12 topics, 61010 documents and a 13914 word dictionary.
```

Created on 2018-05-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

You could make a dataframe with any kind of document-level covariates you need using dplyr, like the one I showed for `book`.

**Comment by mfherman** [comment]
Thanks for this example, Julia. Really helpful! So just to confirm, `stm()` doesn't require the covariate data frame to be in the same order as the sparse matrix?

Although now that I'm looking more closely at the documentation for [`fitNewDocuments()`](https://rdrr.io/cran/stm/man/fitNewDocuments.html), it needs the new documents to be in the stm format. So for this project where I am using a trained stm model to predict document-topic probabilities for new data, I guess I'll need to use the stm format instead of a sparse matrix or a quanteda object.

**Comment by juliasilge** [comment]
As far as I can tell from the code, yes, it uses the row names to find the document IDs, and matches them up. It throws an error if it can't find all the document IDs, or if there are too many.

You are quite right that `fitNewDocuments()` does not yet take more than one kind of input. We talked about that in bstewart/stm#134 and don't have that set up yet.
