### ISSUE TITLE
tidytext::unnest_tokens collapses across vector elements (is there an option to avoid this?)

### ISSUE THREAD

**Issue by jglev** [juliasilge/tidytext#116]
First, thank you for your work on this package!

I've been using the `tidytext::unnest_tokens` function to generate ngrams of various sizes from a vector of survey responses. In this dataset, each response is its own text. This is slightly different than in the ngrams chapter of [*Text Mining with R*](https://www.tidytextmining.com/ngrams.html), where the elements in a vector are each a line of a larger work, and thus able to be collapsed.

After reading the documentation for `unnest_tokens`, I hadn't realized that it will collapse across vector elements. This behavior is shown below, looking for 1-grams through 4-grams:

``` r

library(magrittr)
library(tidytext)
library(tidyverse)
#> ── Attaching packages ────────────────────────────────────── tidyverse 1.2.1 ──
#> ✔ ggplot2 2.2.1     ✔ purrr   0.2.4
#> ✔ tibble  1.4.2     ✔ dplyr   0.7.4
#> ✔ tidyr   0.8.0     ✔ stringr 1.3.1
#> ✔ readr   1.1.1     ✔ forcats 0.3.0
#> ── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
#> ✖ tidyr::extract()   masks magrittr::extract()
#> ✖ dplyr::filter()    masks stats::filter()
#> ✖ dplyr::lag()       masks stats::lag()
#> ✖ purrr::set_names() masks magrittr::set_names()

n_gram_levels <- 1:4

short_texts <- tibble(text = c('test', 'test two', 'test two three'))

n_gram_levels %>% 
  map(
    function(x) {
     short_texts %>% 
      tidytext::unnest_tokens(
        output = ngram,
        input = text,
        token = "ngrams",
        n = x
      )
    }
  )
#> [[1]]
#> # A tibble: 6 x 1
#>   ngram
#>   <chr>
#> 1 test 
#> 2 test 
#> 3 two  
#> 4 test 
#> 5 two  
#> 6 three
#> 
#> [[2]]
#> # A tibble: 5 x 1
#>   ngram    
#>   <chr>    
#> 1 test test
#> 2 test two 
#> 3 two test 
#> 4 test two 
#> 5 two three
#> 
#> [[3]]
#> # A tibble: 4 x 1
#>   ngram         
#>   <chr>         
#> 1 test test two 
#> 2 test two test 
#> 3 two test two  
#> 4 test two three
#> 
#> [[4]]
#> # A tibble: 3 x 1
#>   ngram             
#>   <chr>             
#> 1 test test two test
#> 2 test two test two 
#> 3 two test two three
```

This behavior makes sense; but I suspect I'm not the only user with a use-case that involves not collapsing across vector elements (such that, for bigrams in the example above, the function would return `c('test two', 'test two', 'two three')`). Thus, I have a few questions:

1. Is there an option I've missed to *not* collapse across vector elements?
    1. If not, would you be interested in adding one? I would be happy to contribute! I just want to check whether it's in line with your vision for the package first.
1. Either way, would you be interested in a documentation PR that demonstrates an approach for using the function without collapsing across vector elements? Here's a working example, for getting bigrams out of the vector above:

``` r
## Following an approach at https://stackoverflow.com/a/44796581

library(magrittr)
library(tidytext)
library(tidyverse)
#> ── Attaching packages ────────────────────────────────────── tidyverse 1.2.1 ──
#> ✔ ggplot2 2.2.1     ✔ purrr   0.2.4
#> ✔ tibble  1.4.2     ✔ dplyr   0.7.4
#> ✔ tidyr   0.8.0     ✔ stringr 1.3.1
#> ✔ readr   1.1.1     ✔ forcats 0.3.0
#> ── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
#> ✖ tidyr::extract()   masks magrittr::extract()
#> ✖ dplyr::filter()    masks stats::filter()
#> ✖ dplyr::lag()       masks stats::lag()
#> ✖ purrr::set_names() masks magrittr::set_names()

n_gram_levels <- 1:4

short_texts <- tibble(text = c('test', 'test two', 'test two three'))

short_texts %>% 
  unname() %>% 
  pmap(
    function(x) {
      tidytext::unnest_tokens(
        as.tibble(x),
        output = ngram,
        input = value,
        token = "ngrams",
        n = 2
      )
    }
  ) %>% 
  unlist() %>% 
  as.tibble() %>% 
  rename(ngram = value)
#> # A tibble: 3 x 1
#>   ngram    
#> * <chr>    
#> 1 test two 
#> 2 test two 
#> 3 two three
```

Again, thank you for your work!

**Comment by juliasilge** [comment]
Hello there, @publicus! Thank you so much for your interest in tidytext. 🙌

We do have an option for turning this kind of collapsing off/on in `unnest_tokens()`. It is called `collapse`. In your example, you would use it with `collapse = FALSE` like this, with these results:

``` r
library(tidyverse)

n_gram_levels <- 1:4

short_texts <- tibble(text = c('test', 'test two', 'test two three'))

n_gram_levels %>% 
    map(
        function(x) {
            short_texts %>% 
                tidytext::unnest_tokens(
                    output = ngram,
                    input = text,
                    token = "ngrams",
                    n = x,
                    collapse = FALSE
                )
        }
    )
#> [[1]]
#> # A tibble: 6 x 1
#>   ngram
#>   <chr>
#> 1 test 
#> 2 test 
#> 3 two  
#> 4 test 
#> 5 two  
#> 6 three
#> 
#> [[2]]
#> # A tibble: 4 x 1
#>   ngram    
#>   <chr>    
#> 1 <NA>     
#> 2 test two 
#> 3 test two 
#> 4 two three
#> 
#> [[3]]
#> # A tibble: 3 x 1
#>   ngram         
#>   <chr>         
#> 1 <NA>          
#> 2 <NA>          
#> 3 test two three
#> 
#> [[4]]
#> # A tibble: 3 x 1
#>   ngram
#>   <chr>
#> 1 <NA> 
#> 2 <NA> 
#> 3 <NA>
```

Created on 2018-05-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Notice that you have `NA` values wherever you don't have ngrams of at least that size.

The `collapse` argument is documented for `unnest_tokens()` but the fact that you couldn't find it makes me think that I could do a bit better job surfacing this somewhere. I don't want to add another example to `unnest_tokens()` and none of the vignettes currently explore ngrams at all. Hmmmm... Where were you trying to find this information when you looked for it?

**Comment by jglev** [comment]
@juliasilge, thank you for your reply!

I'm sheepish that I missed that argument! Now that you point it out, I see it, ha. I read/skimmed several times the `?tidytext::unnest_tokens` documentation (but missed the `collapse` argument), read the ngrams chapter of *Text Mining with R,* and Googled "unnest_tokens without collapsing."

Looking back, I think that one aspect that confused me is that the `Details` section of the `?unnest_tokens()` documentation states that

> If the unit for tokenizing is ngrams, skip_ngrams, sentences, lines, paragraphs, or regex, the entire input will be collapsed together before tokenizing.

I skimmed that documentation several times, and missed the argument each time; perhaps changing that sentence to "...unless `collapse = FALSE`" would help to surface it?

Again, thank you for your help! And thank you for your work on `tidytext`; I look up to it!

**Comment by juliasilge** [comment]
That is perfect @publicus! Thank you so much for bringing this to my attention and helping me improve tidytext. 🙏
