### ISSUE TITLE
unnest_tokens error for one word sentence

### ISSUE THREAD

**Issue by fmerhout** [juliasilge/tidytext#119]
I encountered an error when trying to get tokens from previously unnested sentences, if the sentence is only one word. This error occurs when specifying `token` as `tokenize_tweets` but not if I use `token = "words"`. I assumed that this was an issue with the tokenizer package but both `tokenize_words` and `tokenize_tweets` return an error with one word sentences, so I am wondering if there is a workaround to make `unnest_tokens` work with `tokenize_tweets` even if there are one word sentences.

Here is an example:

`unnest_tokens(as.tbl(data_frame(sentences = "Word.")), output = "word", input = "sentences", 
              token = tokenize_tweets, drop = FALSE)`

returns

`Error in cut.default(seq_along(out), docindex, include.lowest = TRUE,  : 
  'breaks' are not unique`

**Comment by kanishkamisra** [comment]
@juliasilge do you think checking for length of input and if it is just a word, using ```tokenize_words``` for single words would work for this?

**Comment by juliasilge** [comment]
The underlying problem has now been fixed in the tokenizers package in the above issue. You can install the fixed version via `devtools::install_github("ropensci/tokenizers")`.

``` r
library(tidytext)
library(tidyverse)

single_word <- data_frame(sentences = "Hello!")

single_word %>%
  unnest_tokens(word, sentences, token = "tweets")
#> # A tibble: 1 x 1
#>   word 
#>   <chr>
#> 1 hello
```

Created on 2018-07-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Thanks so much for the report! 🙌
