### ISSUE TITLE
Moving pair_count (and future related functions) to "widyr" package

### ISSUE THREAD

**Issue by dgrtwo** [juliasilge/tidytext#12]
I've started developing the [widyr](https://github.com/dgrtwo/widyr) package (the docs and examples there are still rather primitive) that handles the common pattern of

```
tidydata -acast->
  matrix -some operation->
  matrix -melt->
  tidydata
```

One notable example of this pattern (what got me onto the topic) is pair_count. I'd thus like to deprecate tidytext's `pair_count` and move it there (and in the new package name it `pairwise_count` just to avoid any future name clash). I think there's a variety of applications and I think it would be easier to experiment and develop them out of the way of text mining applications, especially since tidytext is on CRAN and has active users.

Does this sound reasonable?

**Comment by juliasilge** [comment]
This sounds like a sensible move to make; now that you've pointed this out, the `pair_count` operation isn't really specific to text at all, is it? I am open to this move.

So moving forward, what makes the most sense and is the right thing to do when something like this happens? If the function `pair_count` is not going to live in `tidytext` anymore? What will be the list of things we'll need to do?
- remove example from README and vignette
- move/edit code from `R` folder
- move/edit tests

Anything else? (If you want any specific help with `widyr` or moving things over, I am for sure interested in getting things set up, etc.)

**Comment by dgrtwo** [comment]
Generally a good guide is [here](http://r-pkgs.had.co.nz/release.html) (under "Backwards compatability").

For now I've added a warning to the function, added a note to its docs and to NEWS, and removed mentions from the README.

Now it occurs to me that I've left the test cases, but that it will have a warning. If I remove the test, it will hurt our code coverage (argh!). The best bet in this case _might_ be to make a judgment call that not many people have used this (since we're new and it's a bit obscure) and just remove it entirely.

Any thoughts?

**Comment by juliasilge** [comment]
You mean test cases as in tests using `testthat`? So, the tests shouldn't go in this package if the function isn't in this package, right? We'll get test coverage for the package as a whole back up in the long term, so let's not worry about that right now in this context.

I do feel OK about moving this function at this point, because this is early in the package's use and people aren't really set in their ways with it yet. It will be gone by the second CRAN release.

**Comment by juliasilge** [comment]
OK, I read this all again and am less sick than I was the first time so maybe I am understanding this more. So can you clarify for me -- is "deprecated" different than "deleted"? The function `pair_count` will be deprecated here and we won't do development on it here, but the actual function will still hang around in its current form? Or is this an intermediate step and eventually it will actually be deleted?

**Comment by dgrtwo** [comment]
Glad you're feeling better!

The goal of the first step of deprecation is so that people who are accustomed to using it (e.g. in an old script) get an informative warning instead of wondering why it stopped working. In a following version we'd either replace the warning with a flat error ("use this other function instead") or just remove it entirely. Check out the chapter of R Packages I linked for more!

This is balanced against the simpler solution of hoping no one has really used it yet and just dropping it "down the memory hole".
