### ISSUE TITLE
Trying to compute distinct() for variables not found in the data

### ISSUE THREAD

**Issue by strohne** [juliasilge/tidytext#120]
Hi, with the newest packages installed I encounter a warning, which may be serious. See the last lines:

```
R version 3.4.2 (2017-09-28) -- "Short Summer"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(dplyr)

Attache Paket: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Warning message:
Paket ‘dplyr’ wurde unter R Version 3.4.4 erstellt 
> library(tidytext)
Warning message:
Paket ‘tidytext’ wurde unter R Version 3.4.4 erstellt 
> test <- tibble(
+   no=c(1:5),
+   term =c("für","for","für","for","für"),
+   n=c(1,1,1,1,1)
+ )
> test %>% 
+   cast_dtm(no,term,n)
<<DocumentTermMatrix (documents: 5, terms: 2)>>
Non-/sparse entries: 5/5
Sparsity           : 50%
Maximal term length: 3
Weighting          : term frequency (tf)
Warning message:
Trying to compute distinct() for variables not found in the data:
- `row_col`, `column_col`
This is an error, but only a warning is raised for compatibility reasons.
The operation will return the input unchanged. 
```

Why are there missing columns?

BTW: great package, thank you so much!

**Comment by fmerhout** [comment]
This seems to be related to issue #121. 

I encountered the same warning/error message but it seems that the output is what we would expect, i.e. the returned matrix is the same as we'd get from explicitly calling `sparseMatrix`. 

Might this be an issue with how caster functions pass the row and column name to distinct?

**Comment by lepennec** [comment]
Indeed, there is an error in the `distinct` call, which fails gracefully by returning the original data.frame...

**Comment by rituk** [comment]
> Indeed, there is an error in the `distinct` call, which fails gracefully by returning the original data.frame.. 
I'm still getting this error. Is there a solution?

**Comment by juliasilge** [comment]
@rituk Are you using the latest version from GitHub?

```
devtools::install_github("juliasilge/tidytext")
```

**Comment by rituk** [comment]
I believe via install.packages(tidytext)
Came to GitHub after I got the error.
I’ll try via devtools and let you know.

Thanks.

**Comment by njritter** [comment]
Had same error message when using cast_sparse(). Fixed with devtools::install_github("juliasilge/tidytext").

Thanks Julia!

**Comment by rituk** [comment]
Yes, it was solved for me as well.
Thank you Julia.

**Comment by Viviana** [comment]
I am very grateful -- thanks much, Julia, for solving the issue! :)

**Comment by avidyaN** [comment]
> 
> 
> @rituk Are you using the latest version from GitHub?
> 
> ```
> devtools::install_github("juliasilge/tidytext")
> ```

Julia, is the package still available? I keep getting timed out

**Comment by juliasilge** [comment]
Yep! It certainly is. It doesn't look like GitHub is having any issues right now so it is unlikely to be that side of things.

And I do have a CRAN release with the NSE fixes coming shortly FYI.

**Comment by rituk** [comment]
Yes, I did use/download the same package a few days ago. It worked fine.
