### ISSUE TITLE
Tidy doesn't work, gives this error : No tidy method for objects of class LDA_Gibbs. 

### ISSUE THREAD

**Issue by Mirsatra** [juliasilge/tidytext#127]
I'm new to r, so please don't laugh

Please review the code:
library(NLP)
library(tm)
library(tidytext)
library(stringr)
library(tidyr)
library(topicmodels)
library(tidyverse)

mywords<- read.csv("mystop.csv",header =F,sep = ",")
mywords <- as.character(mywords)
mywords <- c(mywords, stopwords())

filelist = list.files(pattern = ".*.txt")
files <- lapply(filelist,readLines)

(docs <- VCorpus(VectorSource(files)))

docs <-tm_map(docs,content_transformer(tolower))
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removeWords, mywords)

docs <- tm_map(docs, removeWords,stopwords("english"))
docs <- tm_map(docs, stripWhitespace)

toSpace <- content_transformer(function(x, pattern) { return (gsub(pattern, " " , x))})
docs <- tm_map(docs, toSpace, "-")
docs <- tm_map(docs, toSpace, "’")
docs <- tm_map(docs, toSpace, "‘")
docs <- tm_map(docs, toSpace, "•")
docs <- tm_map(docs, toSpace, "”")
docs <- tm_map(docs, toSpace, "“")

#...............
dtm <- DocumentTermMatrix(docs)
rownames(dtm) <- filelist
freq <- colSums(as.matrix(dtm))
length(freq)
ord <- order(freq,decreasing=TRUE)

d <- data.frame(word = names(freq),freq=freq[ord])

new_dtm<-dtm

burnin <- 4000
iter <- 2000
thin <- 500
seed <-list(2003,5,63,100001,765)
nstart <- 5
best <- TRUE
k <- 3
test_lda2 <-LDA(new_dtm,k, method="Gibbs", 
             control=list(nstart=nstart, seed = seed, best=best, 
                          burnin = burnin, iter = iter, thin=thin))

test_lda_td2 <- tidy(test_lda2) <---Error

lda_top_terms2 <- test_lda_td2 %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

lda_top_terms2 %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()
.................................................................

Please tell me why is that happening

**Comment by juliasilge** [comment]
I would never laugh! Thank you for your interest in tidytext. 🙌

This is an error that I have not been able to reproduce, but you are not the only one who has run into it. See [here](https://github.com/juliasilge/tidytext/issues/101) and [here](https://stackoverflow.com/questions/48765936/using-tidytext-and-broom-but-not-finding-tidier-for-lda-vem/) and [here](https://twitter.com/seizeTheData_/status/1035270422542004224). As best as I can tell, this is likely a bug in the topicmodels package, related to S4 registration. You can avoid running into this by *not* saving `.RData` between sessions and [always starting from a fresh R session when you open up work](http://stat545.com/block002_hello-r-workspace-wd-project.html#workspace-and-working-directory).

**Comment by Mirsatra** [comment]
Thanks for help @juliasilge

**Comment by ttdailytt** [comment]
Hi, I have a similar question. Recently, when I used the R mice package to do multiple imputation. When I tried to pool the results using pool() function, R gave the following error message: 

Error: No tidy method for objects of class qr
In addition: Warning messages:
1: In get.dfcom(object, dfcom) : Infinite sample size assumed.
2: 'tidy.numeric' is deprecated.
See help("Deprecated") 
3: `data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
4: 'tidy.numeric' is deprecated.
See help("Deprecated") 
5: 'tidy.numeric' is deprecated.
See help("Deprecated") 
6: 'tidy.numeric' is deprecated.
See help("Deprecated") 
7: 'tidy.numeric' is deprecated.
See help("Deprecated") 
8: 'tidy.numeric' is deprecated.

Mine is a simulation study. It took days to run. So I did load .RData into the environment. In my case, it is not very practical to run everything from the beginning each time. 

Could anyone please help? Thanks in advance.

**Comment by ttdailytt** [comment]
Following the question above, here are packages that I loaded into R"

library(tidyverse) # Includes ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr, forcats
library(extraDistr) # To generate truncated Poisson distribution. 
library(timeDate) # For tidymodels
library(tidymodels) # Plot ROC and Precision-Recall curve. 
library(data.table)
library(sqldf) # Merge multiple datasets. 
library(mice) # multiple imputation
library (tictoc) # To record time. 
library(reconPlots)

**Comment by juliasilge** [comment]
It sounds like you are not using tidytext at all; is that right? You'll likely will need to look to the packages you are using to get help. 

I still recommend that you do not save `.RData` because of these kinds of bugs; instead, follow [best practices around objects that take a long time to create](https://rstats.wtf/save-source.html#objects-that-take-a-long-time-to-create).
