### ISSUE TITLE
Question about licence for sentiment datasets

### ISSUE THREAD

**Issue by ColinFay** [juliasilge/tidytext#131]
Hey, 

I'm currently doing researches around licensing & R packages, and one of the topics is licensing datasets. 

`{tidytext}` contains 4 datasets for sentiment analysis, so I thought I could ask fo help on these topics, as I have some questions about how you proceeded to be sure the datasets used are compatible with the package license.

+ The only info for NRC is "The lexicons listed here are available free for research purposes" (from http://saifmohammad.com/WebPages/lexicons.html), which seems to be incompatible with the MIT license (as far as I have understood MIT) which allows commercial use. How did you proceed for rightly include this dataset in the package? Did you contact the dataset owner? If, what is the process for included this "granting" in the package? 
+ I could not find any explicit licence for the "bing" & "loughran" datasets (https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html & https://sraf.nd.edu/textual-analysis/resources/#LM%20Sentiment%20Word%20Lists), how did you proceed for these ones, contacted the authors? If yes, how did you proceed to reflect that in the package?
+ AFINN is ODBL, which is MIT compatible so this one seems to be easy to include in the package :) 

Thanks a lot for your help on that :) 

Colin

**Comment by juliasilge** [comment]
What a great but complicated topic! I was looking back on when we added these to the package, and the NRC, Bing, and AFINN lexicons were added very early, in the first days of us writing the package at the rOpenSci unconf. If I remember correctly, we looked to see what lexicons other open source packages (R and Python) were using and undertook to embrace the community norms and similar practices. We were able to access these datasets through existing open resources. @dgrtwo does that align with how you remember the decision-making?

When it comes to the Loughran lexicon, I wonder if @dgrtwo could speak more directly to that.

**Comment by jwijffels** [comment]
Great topic! @juliasilge Can you explain a bit more how and where you retrieved the data from and how you converted all these data into MIT license. Depending on what you did in these early days when creating the package, tidytext might have been distributed (illegally) with a wrong license ...
I might be mistaken here but probably these sentiment dictionaries alongside the tidytext package has been used by useRs in commercial settings. If that would be the case, I would be interested to see how you handle this and how you communicate this to the pretty extensive tidytext user base and to the cran maintainers.

**Comment by juliasilge** [comment]
As I'm looking back at how/why we worked with these lexicons, I am noting that the [syuzhet](https://github.com/mjockers/syuzhet) package (a package I'd previously used for sentiment analysis before developing tidytext) included the NRC, Bing, and AFINN lexicons with a GPL-3 license, but noted each of the lexicons' licenses outside of the package's license in https://github.com/mjockers/syuzhet/commit/3a12441b1ebb01802f9d24d0fc4be1ab2b64e883, apparently under instruction from CRAN (see the commit message). We haven't gotten such instruction from CRAN but should look into this issue more.

Perhaps the correct option is to take the same approach, noting each lexicon's license, and to issue a statement about any error we made in omitting this information previously.

**Comment by jwijffels** [comment]
Here is what I would do in such a case
- communicate to the tidytext users that they should only use the sentiment lexicons in situations allowed by the license
- contact the authors of the data to have their opinion on the redistribution of the data in the way tidytext did
- request the cran maintainers to remove the current and archived packages from cran as the license is wrong
- in the tidytext code, factor out the datasets by puting them online somewhere and make a function which downloads them instead of putting them in the package + document the license in that function
- re-release to cran 
good luck!

**Comment by juliasilge** [comment]
Look into using @EmilHvitfeldt's in-process [textdata](https://github.com/emilhvitfeldt/textdata) package to download sentiment datasets, vs. storing them in package.

**Comment by EmilHvitfeldt** [comment]
If you have any questions or suggestions regarding [textdata](https://github.com/emilhvitfeldt/textdata), please let me know!

**Comment by jwijffels** [comment]
@juliasilge have you found time to look into this issue together with cran and the owners of the sentiment data dictionaries?

**Comment by juliasilge** [comment]
Still working on getting details from the sentiment lexicon creators.

From Bing Liu:
> Thanks for the email and for asking. I know but am not familiar with the details of different licenses. As an academic, I am happy that what I do is useful. So, you can just use it in whatever way you see fit as long as there is attribution. The lexicon has also been used in a number of commercial companies for free.

**Comment by jwijffels** [comment]
That sounds to me like that person had cc-by as License in it’s mind. https://creativecommons.org/licenses/by/4.0/. What about NRC and loughran?
