### ISSUE TITLE
AFINN lexicon may need updating

### ISSUE THREAD

**Issue by richierocks** [juliasilge/tidytext#134]
There's a possible typo in the AFINN lexicon ([ominous has a positive score](https://github.com/fnielsen/afinn/issues/23)), so heads up that you'll need to change the score for that word here once that issue is resolved.

**Comment by juliasilge** [comment]
The AFINN lexicon is no longer directly stored within tidytext, as of commit 4502afc4783869799f5036ce3b0164c3549a24ec.
