### ISSUE TITLE
Unnest tokens capture regex

### ISSUE THREAD

**Issue by darrkj** [juliasilge/tidytext#135]
I am more and more using tidytext to break text up into larger chunks than just word. Having the option for token to be a regex and then supply the required regex to the pattern argument is very useful for this but has a strange drawback. I often need aspects of the regex as a new field. In many of the example usages the pattern is something like 'Chapter [\\d]', but the chapter can be recreated since it is a sequential number by adding a new column with something like the row_number() function by document/group. It would be very nice to have another argument that would take the matching string and add it as a new column because often the regex is not something as simple as the number, but once the text is tokenized that string no longer exists to create the field and most of the methods I have thought about require a lot of weird extra steps. 

Here is a simple example, the second result the desired outcome but that approach wont work outside of a small case like this.

```{r}
script <- tibble(text = 'Person 1: Good morning
Person 2: and good morning to you too, and a verbose statement to 
 to show that by line does not work.
Person 1: have a good day
Person 3: hello')

script %>% unnest_tokens(line, text, token = "regex", pattern = "Person \\d\\: ")

# A tibble: 4 x 1
  line                                                                                              
  <chr>                                                                                             
1 "good morning\n"                                                                                  
2 "and good morning to you too, and a verbose statement to \n to show that by line does not work.\n"
3 "have a good day\n"                                                                               
4 hello                                                                                             

script %>% unnest_tokens(line, text, token = "regex", pattern = "Person \\d\\: ") %>% 
   mutate(actor = c('Person 1:', 'Person 2:', 'Person 1:', 'Person 3:')) %>% 
   select(actor, line)

# A tibble: 4 x 2
  actor     line                                                                                              
  <chr>     <chr>                                                                                             
1 Person 1: "good morning\n"                                                                                  
2 Person 2: "and good morning to you too, and a verbose statement to \n to show that by line does not work.\n"
3 Person 1: "have a good day\n"                                                                               
4 Person 3: hello 
```

It also exhibits a bit of the fencepost problem, you would have ten pieces of text and only nine patterns extracted which makes it a bit more complicated. If you could somehow specify which item gets the NA, either the first or the last. It could be the section name which means the first pattern precedes the text, or it could be a page name in which case it trails the text. The unnest tokens function seems like it already handles the edge case of starting and ending with the pattern.

```
tibble(text = ' 1 this is 2 the text 3 ') %>% 
  unnest_tokens(section, text, token = "regex", pattern = "\\d")
# A tibble: 4 x 1
  section     
  <chr>       
1 " "         
2 " this is " 
3 " the text "
4 " "    
     
tibble(text = ' 1 this is 2 the text 3') %>% 
  unnest_tokens(section, text, token = "regex", pattern = "\\d")
# A tibble: 3 x 1
  section     
  <chr>       
1 " "         
2 " this is " 
3 " the text "

tibble(text = '1 this is 2 the text 3 ') %>% 
  unnest_tokens(section, text, token = "regex", pattern = "\\d")
# A tibble: 3 x 1
  section     
  <chr>       
1 " this is " 
2 " the text "
3 " "         

tibble(text = '1 this is 2 the text 3') %>% 
  unnest_tokens(section, text, token = "regex", pattern = "\\d")
# A tibble: 2 x 1
  section     
  <chr>       
1 " this is " 
2 " the text "
```

**Comment by juliasilge** [comment]
Thank you so much for this feedback! 🙌

If I needed to do this task, I don't think I would use tidytext at all, at least not for this section of it:

``` r
library(tidyverse)

script <- tibble(text = 'Person 1: Good morning
Person 2: and good morning to you too, and a verbose statement to 
 to show that by line does not work.
Person 1: have a good day
Person 3: hello')

script %>%
  mutate(line = str_split(text, "Person \\d\\: ")) %>%
  unnest(line) %>%
  mutate(actor = str_extract(text, paste0("Person \\d\\: ", line)),
         actor = str_extract(actor, "Person \\d\\: ")) %>%
  select(actor, line) %>%
  filter(line != "")
#> # A tibble: 4 x 2
#>   actor       line                                                         
#>   <chr>       <chr>                                                        
#> 1 "Person 1:… "Good morning\n"                                             
#> 2 "Person 2:… "and good morning to you too, and a verbose statement to \n …
#> 3 "Person 1:… "have a good day\n"                                          
#> 4 "Person 3:… hello
```

<sup>Created on 2019-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

We certainly *can* get to what you need with the existing tooling, and it should be quite fast because it only uses stringr instead of tidytext. My first instinct is that we want to keep the `unnest_tokens()` behavior as is but let me think about this more.

**Comment by darrkj** [comment]
Thanks for the response, and for all the effort put into tidytext. 

There are definitely other ways to accomplish this type of thing but it just felt weird for a few reasons. The first part is that a minor change to the output is a very large change to the input. If you already use the tidytext approach but only later in an analysis realize that this part is needed the whole strategy needs to be reworked. Then you may also have two different set of data but need to process them differently.

```
library(tidyverse)
library(tidytext)

script <- tibble(text = 'Person 1: Good morning
                 Person 2: and good morning to you too, and a verbose statement to 
                 to show that by line does not work.
                 Person 1: have a good day')

script %>% unnest_tokens(line, text, token = "regex", pattern = "Person \\d\\: ")
#> # A tibble: 3 x 1
#>   line                                                                    
#>   <chr>                                                                   
#> 1 "good morning\n                 "                                       
#> 2 "and good morning to you too, and a verbose statement to \n            …
#> 3 have a good day

script %>% 
  mutate(line = str_split(text, "Person \\d\\: ")) %>%
  unnest(line) %>%
  mutate(actor = str_extract(text, paste0("Person \\d\\: ", line)),
         actor = str_extract(actor, "Person \\d\\: ")) %>%
  select(actor, line) %>%
  filter(line != "")
#> # A tibble: 3 x 2
#>   actor        line                                                       
#>   <chr>        <chr>                                                      
#> 1 "Person 1: " "Good morning\n                 "                          
#> 2 "Person 2: " "and good morning to you too, and a verbose statement to \…
#> 3 "Person 1: " have a good day
```

I was thinking it would be very clean and follow many of the other tidy aspects to have a smaller change to get the required output. Something like the code below was what came to mind was just just adding or setting an argument, I do realize this could be a larger change to the function implementation though which may not be desirable. I notice this pattern a lot in tidyverse functions, the one that comes to mind is spread, when I use that and see that certain items have an NA I can use the fill argument to fix it as opposed to backing up and going down a different path.

```
script %>% unnest_tokens(line, text, token = "regex", pattern = "Person \\d\\: ", .keep = T)
```

Perhaps a bigger issue is that unnest_tokens already does lots of things in a robust way, whereas stringr is more generic which means other things need to be considered. For instance if the input data changes just a bit, which now looks more like real data, odd things happen while the tidytext output still looks good. The first result loses the actor because of the parenthesis or slashes. This would require cleaning all non-actor portions of the text by escaping them because the first part relies on the regular expression so the whole thing has to be a regular expression. The second item wont even create a result for a similar reason as the last case.

```
library(tidyverse)
library(tidytext)

script <- tibble(text = 'Person 1: Good morning
                 Person 2: and good morning to you too, and a verbose statement to 
                 to show that by line does not work.
                 Person 1: have a good day
                 Person 2: and (odd) things
                 Person 1: more \\odd things
                 Person 2: and [crazy things')

script %>% unnest_tokens(line, text, token = "regex", pattern = "Person \\d\\: ")
#> # A tibble: 6 x 1
#>   line                                                                    
#>   <chr>                                                                   
#> 1 "good morning\n                 "                                       
#> 2 "and good morning to you too, and a verbose statement to \n            …
#> 3 "have a good day\n                 "                                    
#> 4 "and (odd) things\n                 "                                   
#> 5 "more \\odd things\n                 "                                  
#> 6 and [crazy things

script %>% mutate(text = substr(text, 1, 290)) %>% 
  mutate(line = str_split(text, "Person \\d\\: ")) %>%
  unnest(line) %>%
  mutate(actor = str_extract(text, paste0("Person \\d\\: ", line)),
         actor = str_extract(actor, "Person \\d\\: ")) %>%
  select(actor, line) %>%
  filter(line != "")
#> # A tibble: 5 x 2
#>   actor        line                                                       
#>   <chr>        <chr>                                                      
#> 1 "Person 1: " "Good morning\n                 "                          
#> 2 "Person 2: " "and good morning to you too, and a verbose statement to \…
#> 3 "Person 1: " "have a good day\n                 "                       
#> 4 <NA>         "and (odd) things\n                 "                      
#> 5 <NA>         "more \\odd things"

script %>% 
  mutate(line = str_split(text, "Person \\d\\: ")) %>%
  unnest(line) %>%
  mutate(actor = str_extract(text, paste0("Person \\d\\: ", line)),
         actor = str_extract(actor, "Person \\d\\: ")) %>%
  select(actor, line) %>%
  filter(line != "")
#> Error in mutate_impl(.data, dots): Evaluation error: Missing closing bracket on a bracket expression. (U_REGEX_MISSING_CLOSE_BRACKET).
```

I think the tidytext method is probably still easier than the stringr method if we couple it with stringr for one small part. This does the extraction in a mutate step and adds it as a variable. I don't know all of the implementation details but was curious if an argument like the one above could actually do something like this on the original input before the function returns the result.

```
script %>% 
  unnest_tokens(line, text, token = "regex", pattern = "Person \\d\\: ") %>% 
  mutate(actor = str_extract_all(script$text, "Person \\d\\: ") %>% unlist) %>% 
  select(actor, line)
#> # A tibble: 6 x 2
#>   actor        line                                                       
#>   <chr>        <chr>                                                      
#> 1 "Person 1: " "good morning\n                 "                          
#> 2 "Person 2: " "and good morning to you too, and a verbose statement to \…
#> 3 "Person 1: " "have a good day\n                 "                       
#> 4 "Person 2: " "and (odd) things\n                 "                      
#> 5 "Person 1: " "more \\odd things\n                 "                     
#> 6 "Person 2: " and [crazy things
```

**Comment by juliasilge** [comment]
Thank you for your patience as I stepped away from this for a while! I spent some time working through some options for possibly implementing this, and I've decided, at least for now, not to add an option for capturing the regex directly from tidytext. The main reason is that [with the way splitting is implemented](https://github.com/ropensci/tokenizers/blob/ca1674a83dfba02984e721c0f1c0bfd55d747495/R/basic-tokenizers.R#L243), the regex is identified as the boundary between tokens and not with either the token before or after the regex. It's possible to extract the regexes but it's not clear from data coming in where to keep that bit of text data moving forward. I played around with a few solutions, using your example data, the `Chapter` example, etc, and it doesn't look like there are general solutions that can be implemented in a clear way.

My take on this right now is that finding/cleaning these regex pieces is more part of the data cleaning/reshaping process, and it is too unique and specific to an individual dataset for a general solution with something like a `.keep` argument. If you'd like to see a bit about why this is, you can check out [how the `unnest_tokens()` is implemented](https://github.com/juliasilge/tidytext/blob/525c1f74bd0529f6950a713c878b13245787d44b/R/unnest_tokens.R#L169).

Thank you so much for your thoughtful feedback and use of this package! 🙏
