### ISSUE TITLE
Shortcuts functions for unnest_tokens

### ISSUE THREAD

**Issue by ColinFay** [juliasilge/tidytext#137]
[Confession time]

I can never remember how to correctly specify the arguments when using the `unnest_tokens` function for more than tokenizing unigrams. 

'Is it written "ngrams" or "ngram"'? What's the argument for passing number again? Ok I seem to remember a way to remove punctuation when tokenizing tweets, what's the argument?". And many times I have to go to the tidytext documentation, then to the tokenizer documentation just to be sure how to correctly specify the arguments.

[Confession off]

I think `unnest_token` is an amazing function but the fact that it can work on a various amount of format and with a wide variety of arguments makes it a little bit hard to remember.

How would you feel about implementing functions like `unnest_ngrams`, or `unnest_tweets` that would be wrappers around `unnest_tokens()` but with a more easy to remember syntax? 

I think a series of functions like : 

``` r
library(tidytext)
library(rlang)

unnest_ngrams <- function(
  tbl, 
  output, 
  input, 
  n = 3L, 
  n_min = n, 
  stopwords = character(), 
  ngram_delim = " ", 
  simplify = FALSE,
  format = c("text", "man", "latex", "html", "xml"), 
  to_lower = TRUE, 
  drop = TRUE, 
  collapse = NULL
){
  format <- match.arg(format)
  unnest_tokens(tbl, 
                !! enquo(output), 
                !! enquo(input), 
                format = format, 
                to_lower = to_lower, 
                drop = to_lower, 
                collapse = to_lower, 
                token = "ngrams", 
                n = n, 
                n_min = n_min, 
                stopwords = stopwords, 
                ngram_delim = ngram_delim, 
                simplify = simplify
                )
}

unnest_ngrams(proustr::albertinedisparue, bigrams, text, n = 2)
#> # A tibble: 106,149 x 4
#>    book               volume       year bigrams               
#>    <chr>              <chr>       <dbl> <chr>                 
#>  1 Albertine disparue Tome Unique  1925 mademoiselle albertine
#>  2 Albertine disparue Tome Unique  1925 albertine est         
#>  3 Albertine disparue Tome Unique  1925 est partie            
#>  4 Albertine disparue Tome Unique  1925 partie comme          
#>  5 Albertine disparue Tome Unique  1925 comme la              
#>  6 Albertine disparue Tome Unique  1925 la souffrance         
#>  7 Albertine disparue Tome Unique  1925 souffrance va         
#>  8 Albertine disparue Tome Unique  1925 va plus               
#>  9 Albertine disparue Tome Unique  1925 plus loin             
#> 10 Albertine disparue Tome Unique  1925 loin en               
#> # … with 106,139 more rows
```

<sup>Created on 2019-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

would be awesome.

[EDIT 2019-08-01]

Here is a list of possible tokens, which can get a wrapper: 

+ [ ] "words" (default)
+ [x] "characters"
+ [x] "character_shingles"
+ [x] "ngrams"
+ [x] "skip_ngrams"
+ [x] "sentences"
+ [x] "lines"
+ [x] "paragraphs"
+ [x] "regex"
+ [x] "tweets" 
+ [x] "ptb"

**Comment by juliasilge** [comment]
Thank you so much for this feedback @ColinFay and also for your patience as it took me a while to respond here.

I can definitely see the value of making some wrapper functions, because the documentation for `unnest_functions()` is very information dense and sometimes users miss important tidbits of helpful things to know. This could be a nice way to provide some more user friendly function calls and documentation, autocomplete options in RStudio, etc.

Are you interested in writing some of these helper functions and submitting them as a PR (adding yourself as `ctb`)? I know it's been quite a while so if your interest has passed, that is no problem.

**Comment by ColinFay** [comment]
Sure, I'll be happy to do that. 

I'm on holidays next week, but I'll start working on that after that :)

**Comment by juliasilge** [comment]
Hello there @ColinFay! 👋 Are you still interesting in working on these wrapper functions and submitting a PR? Either way is absolutely OK! If you are going to decline, I think I may put them together, or @EmilHvitfeldt has also expressed some interest.

**Comment by ColinFay** [comment]
Hi, 

Sorry I procrastinated on that. 

I've update my original comment with the list of possible tokens. I'll start working on this today, and will send you one PR by function so that it's easier to review :)

**Comment by juliasilge** [comment]
Thank you so much for all your work on this @ColinFay! 🙌 I appreciate it so much!

I am thinking we don't need to have a wrapper function for `"words"` since the default `unnest_tokens()` acts in that way anyway. Let's call this finished! ✅
