### ISSUE TITLE
Could not install tidytext from github

### ISSUE THREAD

**Issue by sagitaninta** [juliasilge/tidytext#138]
Hi Julia, thanks for this amazing package, especially the `reorder_within()` function that I have been looking for.  I was seeing your demo with `stm` and [you said that the function was still on the development version](http://disq.us/p/1ye1bj3) of `tidytext` so that to get it we need to install `tidytext` using `devtools::install_github`. However, I encountered error while doing that:

```
> devtools::install_github("juliasilge/tidytext")
Downloading GitHub repo juliasilge/tidytext@master
juliasilge-tidytext-becd24c/inst/extdata/books.rda: truncated gzip input
tar.exe: Error exit delayed from previous errors.
�tar.exe -zxf "C:\Users\Public\Documents\Wondershare\CreatorTemp\RtmpwFN2Vd\file4494699e7056.tar.gz" -C "C:/Users/Public/Documents/Wondershare/CreatorTemp/RtmpwFN2Vd/remotes44944371443c"� returned error code 1running command 'tar.exe -ztf "C:\Users\Public\Documents\Wondershare\CreatorTemp\RtmpwFN2Vd\file4494699e7056.tar.gz"' had status 1Error: Does not appear to be an R package (no DESCRIPTION)
```

I don't really understand what happening; does this mean your `tidytext`'s github could not be installed because it could not be read by `devtools` as a package or is there something with my internet connection? (This is my fourth attempt running `devtools::install_github("juliasilge/tidytext")` to no avail).

Many thanks for your help!

**Comment by juliasilge** [comment]
I've never seen this error before! Have you been able to install other packages via devtools or the newer [remotes](https://cran.r-project.org/package=remotes) package?

Have you checked out [whether you are using a non-standard version of tar](https://github.com/r-lib/devtools/issues/1939)? That issue might have some ideas of things to try, i.e. setting `Sys.setenv("TAR" = "internal")`.

**Comment by juliasilge** [comment]
Hello there, @sagitaninta! Have you solved this problem or been able to look at it again?

**Comment by juliasilge** [comment]
Let me know if you still have installation problems!
