### ISSUE TITLE
unnest_tokens does NOT preserve URLs in tweets

### ISSUE THREAD

**Issue by Selbosh** [juliasilge/tidytext#139]
According to the documentation for `unnest_tokens`,

> ... "tweets" (tokenization by word that preserves usernames, hashtags, and URLS )

This suggests that if I set `token = 'tweets'`, I can rest assured that URLs will remain intact.
However, this is not the case if `to_lower = TRUE`, because many URLs, unlike usernames and hashtags, are case sensitive.

Example
---------

```r
df <- data.frame(id = 1:3,
                 txt = c('I am a regular Tweet!',
                          '#Hashtag @Mention Hello http://t.co/12ABCabc_4',
                          'Foo bar. Baz.'),
                 stringsAsFactors = FALSE)

tidytext::unnest_tokens(df, tokens, txt, token = 'tweets')
```
Output:
```
    id                 tokens
1    1                      i
1.1  1                     am
1.2  1                      a
1.3  1                regular
1.4  1                  tweet
2    2               #hashtag
2.1  2               @mention
2.2  2                  hello
2.3  2 http://t.co/12abcabc_4
3    3                    foo
3.1  3                    bar
3.2  3                    baz
```

If you were to try to follow the new, lowercase URL, it would be broken (or lead somewhere else), because most URL shortening services are case sensitive. This is not a problem when `to_lower = FALSE`.

Solution
---------
I think we should either 
1. update the documentation to make this clear, or
2. somehow preserve the casing of URLs

Whilst it is true that top-level web addresses are case insensitive (`GOOGLE.COM == google.com`), most on Twitter have passed through URL shortening services, and this problem is specific to the `tweets` tokenizer.

**Comment by juliasilge** [comment]
Thanks so much for this report @Selbosh! 🙌

I have added a line to the documentation to make this clear, as well as a `message()` to the user when they use this combination of arguments:

``` r
df <- data.frame(id = 1:3,
                 txt = c('I am a regular Tweet!',
                          '#Hashtag @Mention Hello http://t.co/12ABCabc_4',
                          'Foo bar. Baz.'),
                 stringsAsFactors = FALSE)

tidytext::unnest_tokens(df, tokens, txt, token = 'tweets')
#> Using `to_lower = TRUE` with `token = 'tweets'` may not preserve URLs.
#>     id                 tokens
#> 1    1                      i
#> 1.1  1                     am
#> 1.2  1                      a
#> 1.3  1                regular
#> 1.4  1                  tweet
#> 2    2               #hashtag
#> 2.1  2               @mention
#> 2.2  2                  hello
#> 2.3  2 http://t.co/12abcabc_4
#> 3    3                    foo
#> 3.1  3                    bar
#> 3.2  3                    baz
```

<sup>Created on 2019-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
