### ISSUE TITLE
Extending the library to other languages

### ISSUE THREAD

**Issue by ferzcam** [juliasilge/tidytext#140]
Hello. 

I am currently working on sentiment analysis and I would like to use your work. However, I need to work in Spanish. Thus, I would like to know what steps are necessary to extend your library into another language. I was thinking that changing the sentiments.csv file was enough but I am not sure.

**Comment by EmilHvitfeldt** [comment]
Hello Fernando!

Doing text analysis in Spanish is not going to be that different than in English. The word tokenization done by `unnest_tokens()` will mainly split tokens according to whitespace, which should be fine for you in Spanish.

if you are planing to remove stop words remember to use a Spanish stop words list.

```
stopwords::stopwords("es")
```

and you would need a spanish sentiment lexicon, one such can be found here https://www.kaggle.com/rtatman/sentiment-lexicons-for-81-languages.

> It is distributed here under the GNU General Public License. Note that this is the full GPL, which allows many free uses, but does not allow its incorporation into any type of distributed proprietary software, even in part or in translation. For commercial applications please contact the dataset creators.
