### ISSUE TITLE
NRC not found: Error in match.arg(lexicon) : 'arg' should be one of “afinn”, “bing”, “loughran”

### ISSUE THREAD

**Issue by visamsundaram** [juliasilge/tidytext#141]
In the recent version of tidytext, "NRC" lexicon doesn't seem to work. Is there a way to access previous versions?

**Comment by mrmvergeer** [comment]
alternatively you can use the R package  syuzhet which contains the NRC lexicon: https://cran.r-project.org/web/packages/syuzhet/index.html

**Comment by EmilHvitfeldt** [comment]
The newest version of **tidytext** addressed the problem that NRC was included in the package without proper licenses. Please see http://saifmohammad.com/WebPages/lexicons.html#terms "Do not redistribute the data.".

This resulted in remove the NRC dataset from the package.

We are currently working to get permission to provide the dataset but for now you will have to go directly to the source and download the lexicon there.

**Comment by juliasilge** [comment]
Thanks for your interesting in tidytext @visamsundaram! You can read more about the decision to [remove the NRC lexicon here](https://juliasilge.com/blog/sentiment-lexicons/). The short answer is that currently, no, we won't have the NRC lexicon available and we recommend that you either use a different lexicon or download the lexicon directly from the creator, if you can use it under the terms laid out there.
