### ISSUE TITLE
get_sentiment() fails for afinn and nrc

### ISSUE THREAD

**Issue by tsoukinator** [juliasilge/tidytext#147]
Unsure if either if these issues are on your end, however upon using the get_sentiments() function, I no longer have success calling afinn or nrc sources.

Afinn: http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=6010 
"Database not available"

nrc: http://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm
trying URL 'http://sentiment.nrc.ca/lexicons-for-research/NRC-Emotion-Lexicon.zip'
InternetOpenUrl failed: 'The operation timed out'Error in download.file(url = "http://sentiment.nrc.ca/lexicons-for-research/NRC-Emotion-Lexicon.zip",  : 
  cannot open URL 'http://sentiment.nrc.ca/lexicons-for-research/NRC-Emotion-Lexicon.zip'

**Comment by EmilHvitfeldt** [comment]
Hello @tsoukinator!

The problems are not associated with tidytext, or [textdata](https://github.com/emilhvitfeldt/textdata) which is used underneath the hood to fetch the data.

### Afinn
the download link at the moment is:
http://www2.imm.dtu.dk/pubdb/views/edoc_download.php/6010/zip/imm6010.zip
which gives me

```
Table './pubs_db/t_downloads' is marked as crashed and last (automatic?) repair failed
```

I will suggest waiting a couple of days, if the problems haven't been fixed I'll be in contact with the authors to try figure it out why the link isn't working, but I'm thinking it will come back up again anytime soon.

### nrc

It appears to be working for me. Do note that the download takes a VERY long time right now. In the next coming update I'll change the download link to a different/faster one per request from the authors. I'll suggest waiting a couple of hours and try again (with fairly stable internet).

**Comment by sianteesdale** [comment]
Hello @EmilHvitfeldt,

I have just tried to download the AFINN zipfile today from textdata, and I am getting the same message as @tsoukinator.  As it has been a couple of days since your last reply, would you be able to contact the authors?

**Comment by EmilHvitfeldt** [comment]
Hello @tsoukinator and @sianteesdale,

I'll try to get in contact with the author to fix this problem when I get home from work today. I'll keep everything up to date!

**Comment by EmilHvitfeldt** [comment]
The Afinn lexicon is working again!

I have update the download link for NRC and the faster method can now be used from the developmental version

```
# install.packages("remotes")
remotes::install_github("EmilHvitfeldt/textdata")
```

**Comment by juliasilge** [comment]
Thanks for reporting this! It is now fixed. 👍
