### ISSUE TITLE
Question about incorporating the number of occurrences of the same word when calculating the sentiment

### ISSUE THREAD

**Issue by Ledolter** [juliasilge/tidytext#159]
I am working on sentiment analysis, and I have been using your tidytext software. Which I like very much!
The following question came up. When matching text words to the dictionary, I noticed that repeated words are counted only once. See the enclosed sample program. My question is whether there is a simple trick to actually have the words counted multiple times when counting up the number of positive and negative words.
There may be an easy fix – I just don’t know.
I would appreciate it very much if you could respond to this query.

library(tidytext)
library(janeaustenr)
library(dplyr)
library(stringr) 
library(tidyr) 
library(ggplot2)

############################ three sentiment dictionaries ################################

bing<- get_sentiments("bing") 
bing
bing[1:20,]

nrc<- get_sentiments("nrc") 
nrc
nrc[1:20,]
nrc_joy<- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")
nrc_joy
nrc_joy[1:20,]

afinn<- get_sentiments("afinn") 
afinn
afinn[1:20,]

#######################

## loading the first letter
carr="Langenwang Pichlwang Christmas walking lakeshore abnormal abolish abnormal abnormal abundance abundance abundant"

carr=tolower(carr)		
carr=gsub("[.]","", ignore.case = TRUE,carr) 	
carr=gsub("[,]","", ignore.case = TRUE,carr) 	
carr=gsub("[;]","", ignore.case = TRUE,carr) 	
carr

library(tm) ## for creating the corpus and the document term matrix 
corpus <- VCorpus(VectorSource(carr),readerControl = list(reader = readPlain)) 
corpus1 <- tm_map(corpus, stripWhitespace)
corpus2 <- tm_map(corpus1, content_transformer(tolower))	
corpus3 <- tm_map(corpus2, removePunctuation)
corpus4 <- tm_map(corpus3, removeNumbers)
corpus5 <- tm_map(corpus4, removeWords, stopwords("english"))
corpcarr.dtm <- DocumentTermMatrix(corpus5,control=list(stemming=FALSE)) 
dim(corpcarr.dtm)
lettercarr=tidy(corpcarr.dtm)
lettercarr
colnames(lettercarr)
colnames(lettercarr)[colnames(lettercarr)=="term"]="word"
colnames(lettercarr)
lettercarr

## obtaining (bing) sentiment information for lettercarr
lettercarr_sentiment=lettercarr %>%
  inner_join(bing)%>% 
  count(document,sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = 100*positive/(positive + negative))
lettercarr_sentiment  ## frequencies of (bing) sentiment words

**Comment by juliasilge** [comment]
Hmmm, I think something is going wrong in your data munging/handling, and it may be simpler to use tidy data principles from the start rather than using tm and tidying back and forth.

This approach to sentiment analysis does in fact keep each occurrence of each word with a sentiment score.

``` r
library(tidyverse)
library(tidytext)

carr <- tibble(text = c("Langenwang Pichlwang Christmas walking lakeshore abnormal abolish abnormal abnormal abundance abundance abundant"))

tidy_car <- carr %>%
  unnest_tokens(word, text)
                   
tidy_car
#> # A tibble: 12 x 1
#>    word      
#>    <chr>     
#>  1 langenwang
#>  2 pichlwang 
#>  3 christmas 
#>  4 walking   
#>  5 lakeshore 
#>  6 abnormal  
#>  7 abolish   
#>  8 abnormal  
#>  9 abnormal  
#> 10 abundance 
#> 11 abundance 
#> 12 abundant

tidy_car %>% 
  inner_join(get_sentiments("bing")) 
#> Joining, by = "word"
#> # A tibble: 7 x 2
#>   word      sentiment
#>   <chr>     <chr>    
#> 1 abnormal  negative 
#> 2 abolish   negative 
#> 3 abnormal  negative 
#> 4 abnormal  negative 
#> 5 abundance positive 
#> 6 abundance positive 
#> 7 abundant  positive
```
Notice that words are in there twice.

And then you can find the net sentiment.

```r
tidy_car %>% 
  inner_join(get_sentiments("bing")) %>%
  count(sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive / (positive + negative))
#> Joining, by = "word"
#> # A tibble: 1 x 3
#>   negative positive sentiment
#>      <dbl>    <dbl>     <dbl>
#> 1        4        3     0.429
```

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Ledolter** [comment]
Thanks very much. Very helpful. I figured things out. Best wishes Johannes
