### ISSUE TITLE
purrr >= 0.1.1 is required

### ISSUE THREAD

**Issue by jirkalewandowski** [juliasilge/tidytext#16]
(tidytext is an awesome package, thanks for that!)

When purrr 0.1.0 is installed, tidytext loads fine, but `tidy.Corpus` does not work, since `purr::transpose` is not found. It was ([see here](https://github.com/hadley/purrr/commit/e66b6055aea05b60bbc69713d7310c8d0d92480c)) introduced only with version 0.1.1 of purrr -- so this should go into the DESCRIPTION of tidytext, I think.

**Comment by juliasilge** [comment]
Thanks for drawing this to our attention!
