### ISSUE TITLE
unable to download lexicons required by get_sentiments("nrc") 

### ISSUE THREAD

**Issue by joepowers16** [juliasilge/tidytext#161]
`get_sentiments("nrc")` produces a "Do you want to download" message, and when I type "1" for yes, I am getting this error message:

```
Error: [ENOENT] Failed to make directory '~/Documents': no such file or directory
```

But I do have a Documents directory in my home folder. So I am not sure what is triggering the error.

**Comment by juliasilge** [comment]
Thank you for using tidytext @joepowers16! 🙌 

Downloading the datasets like sentiment lexicons is done by code in **textdata**, and unfortunately I haven't seen this particular style of problem before. Can you submit [this problem as an issue there](https://github.com/EmilHvitfeldt/textdata/issues)? We'll see what we can get figured out over there.

**Comment by joepowers16** [comment]
Thank you @juliasilge, this issue was being caused by a bug in my local environment.
