### ISSUE TITLE
Dependency Error installing "tidytext": 'ISOcodes' and 'stopwords' not available

### ISSUE THREAD

**Issue by hermantoh** [juliasilge/tidytext#163]
Hi, 

I am using OS X Yosemite v10.10.5, R v3.3.3, Rstudio v1.0.153.  I am unable to install package "tidytext" and received below prompt.  Any advise what I should do?

====================

Warning in install.packages :
  dependency ‘ISOcodes’ is not available
also installing the dependency ‘stopwords’

  There are binary versions available but the source versions are later:
          binary source needs_compilation
stopwords  0.9.0    1.0             FALSE
tidytext   0.1.3  0.2.2             FALSE

installing the source packages ‘stopwords’, ‘tidytext’

trying URL 'http://cran.rstudio.com/src/contrib/stopwords_1.0.tar.gz'
Content type 'application/x-gzip' length 104532 bytes (102 KB)
==================================================
downloaded 102 KB

trying URL 'http://cran.rstudio.com/src/contrib/tidytext_0.2.2.tar.gz'
Content type 'application/x-gzip' length 3088493 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

ERROR: dependency ‘ISOcodes’ is not available for package ‘stopwords’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/stopwords’
Warning in install.packages :
  installation of package ‘stopwords’ had non-zero exit status
ERROR: dependency ‘stopwords’ is not available for package ‘tidytext’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tidytext’
Warning in install.packages :
  installation of package ‘tidytext’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/jl/ftld7lnj0bz3phtjb35rzx380000gp/T/RtmpRxqGcJ/downloaded_packages’

**Comment by juliasilge** [comment]
It looks like you need to install the package [ISOcodes](https://cran.r-project.org/package=ISOcodes):

```r
install.packages("ISOcodes")
```

Once you do that, try again! 👍

**Comment by hermantoh** [comment]
Thank you, Julia.  I'm on it.  My R is v3.3.3, and current ISOcodes pkg is for R v3.5.0 or higher.  Is there a quick way to determine which old version is the correct version for me (there are ~ 25 of these older version; there must be a better way than trying it one-by-one (many thanks in advance)?

![image](https://user-images.githubusercontent.com/55031643/74672631-f2327e00-516a-11ea-84e1-e9b663e5aa27.png)

**Comment by hermantoh** [comment]
I got it!  Thank you so much, Julia.  It was just one version earlier.  I did open one-by-one and read the description.  Many thanks; I am grateful for your help.

**Comment by juliasilge** [comment]
Glad you got it figured out!

**Comment by Cosmopal** [comment]
Hi,
I cannot install tidytext because I keep getting the following failure in installing stopwords:

```Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'has_package_doc' not found
Error: unable to load R code in package ‘stopwords’```

This issue originally asked both for ISOcodes and stopwords, but solution is there only for ISOcodes.


I tried installing stopwords separately, but still the same issue.

**Comment by juliasilge** [comment]
@Cosmopal Can you open an issue on the [stopwords GitHub repo](https://github.com/quanteda/stopwords)? Feel free to mention that I sent you.

**Comment by juliasilge** [comment]
Or maybe add your particular problem to quanteda/stopwords#34. Are you on an older version of R?

**Comment by Cosmopal** [comment]
Hi,
I cannot install tidytext because I keep getting the following failure in installing stopwords:

```Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'has_package_doc' not found
Error: unable to load R code in package ‘stopwords’
```

This issue originally asked both for ISOcodes and stopwords, but solution is there only for ISOcodes.


I tried installing stopwords separately, but still the same issue.

**Comment by juliasilge** [comment]
Hello there, @Cosmopal! You added the above comment to the same tidytext issue, not to the stopwords issue. Want to [add it over there](https://github.com/quanteda/stopwords/issues/34)?

**Comment by JosephCrispell** [comment]
This thread is at the top of the google hits for searching "R stopwords object 'has_package_doc' not found". As @juliasilge says head to the stopwords [github](https://github.com/quanteda/stopwords/issues/34) for the answer.

Just in case the solution there is to **install the latest version of R (4.0.0)**.

**Comment by Cosmopal** [comment]
Okay @juliasilge @JosephCrispell I'll add this there. You are right, this is a stopwords installation issue

Thanks for your prompt response, apologies for the delay on my part.

**Comment by juliasilge** [comment]
I have since realized that the problem is the [ISOcodes](https://cran.r-project.org/package=ISOcodes) package, a dependency of stopwords. ISOcodes requires R >= 3.5.0. I am considering moving stopwords to Suggests in tidytext so that tidytext can at least be installed for older versions of R.

**Comment by Cosmopal** [comment]
> ISOcodes requires R >= 3.5.0.

@juliasilge I was working R 3.6.0, so it should still have worked. Yes, moving stopwords to Suggests would really help. In my case, the dataset was already preprocessed, which is why it was annoying to be depending on stopwords, which I didn't even need!

> Just in case the solution there is to install the latest version of R (4.0.0).

@JosephCrispell thanks! I'll try version 4.0. The same thing was mentioned in the Github issue of stopwords. But, it does seem tedious being forced update to 4.0 considering it's a fairly recent release.

**Comment by juliasilge** [comment]
Ah OK, thanks for the details. 👍

**Comment by Cosmopal** [comment]
@juliasilge Thanks a lot for your help! :)
