### ISSUE TITLE
Keep punctuation during ngrams analysis

### ISSUE THREAD

**Issue by Malichot** [juliasilge/tidytext#164]
Dear all,

Thanks a lot and congratulations for developing this wonderful package !
I was wondering if there was a way to keep the punctuation in the `unnest_tokens()` function with the `strip_punct = FALSE` parameter when doing ngrams analysis. I know it is possible when using the function with `words` and `tweets` (Cf. Documentation : [https://www.rdocumentation.org/packages/tidytext/versions/0.2.2/topics/unnest_tokens](url)) but I would like to do that when doing the ngram analysis where each punctuation is considered as a gram.

Thanks a lot !!

**Comment by juliasilge** [comment]
Currently the [underlying tokenizer engine we are using for n-grams](https://docs.ropensci.org/tokenizers/reference/ngram-tokenizers.html) does not support an option for including/not including punctuation. 😕So the answer is not right now, unfortunately! 

I am interested to know if this is a feature folks would like to use, however.

**Comment by Malichot** [comment]
Dear Julia,

Thank you very much for your prompt response! It's a pity ;) 

One of my ideas would be to tidy up the data by keeping the punctuation and then aggregate each line by the number of ngram we want. That way we use the parameter `strip_punct = FALSE` when we split the tokens into unigrams and then we would divide our dataframe into the number of ngrams we want. 
Seems doable on paper, but I'm trying to find a way to actually do this and so far without success...! Can't find a way to aggregate rows in dataframe of characters by a specific value...

**Comment by juliasilge** [comment]
Ah, I may not be entirely understanding your goal, but I do want to make sure you know about the [`collapse` argument for `unnest_tokens()`](https://juliasilge.github.io/tidytext/reference/unnest_tokens.html), in case that solves your problem. You can set `collapse = FALSE` to **not** collapse across lines.

**Comment by EmilHvitfeldt** [comment]
What you can do is create a custom tokenizer function that does what you want and pass that function to the `token` argument in `unnest_tokens`. Luckily this style of tokenization can easily be done in quanteda.

``` r
library(quanteda)
#> Package version: 1.5.2
#> Parallel computing: 2 of 12 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View
txt <- c("this, is tthe text! with some punctuation.", "with one more here")

fun <- function(x) {
  tokens <- quanteda::tokens(x)
  quanteda::tokens_ngrams(tokens)
}

library(tidytext)
library(tibble)

tibble(txt = txt) %>%
  unnest_tokens(tokens, txt, token = fun)
#> # A tibble: 12 x 1
#>    tokens          
#>    <chr>           
#>  1 this_,          
#>  2 ,_is            
#>  3 is_tthe         
#>  4 tthe_text       
#>  5 text_!          
#>  6 !_with          
#>  7 with_some       
#>  8 some_punctuation
#>  9 punctuation_.   
#> 10 with_one        
#> 11 one_more        
#> 12 more_here
```

<sup>Created on 2020-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Malichot** [comment]
Dear Julia Silge and EmilHvitfeldt,

Thanks a lot to both of you for your quick responses !! Unfortunately, I start from corpora that are already in tidy format (morphosyntactic features in csv format with 'word / lemma / part-of-speech tag')  and your solution Emil does not work for that (or I don't seem to be able to make it work ;) ). I'm trying to switch from a corpus in this form :

``` r
> corpus
mots
1    Voilà
2       sa
3    force
4        .
5       Il
6       va
7       de
8       la
9      vie
10       à
11      la
12    mort
13       .
14  Hommes
15       ,
16   bêtes
17       ,
18  villes
19      et
20  choses
21       ,
22    tout
23     est
24 imaginé
```

To a corpus in this form, but with the punctuation as a gram : 

``` r
> corpus_grams
            ngram
1        Voilà sa
1.1      sa force
1.2      force Il
1.3         Il va
1.4         va de
1.5         de la
1.6        la vie
1.7         vie à
1.8          à la
1.9       la mort
1.10  mort Hommes
1.11 Hommes bêtes
1.12 bêtes villes
1.13    villes et
1.14    et choses
1.15  choses tout
1.16     tout est
1.17  est imaginé
```

That's why one of my idea was to merge rows 2 by 2 from the unigram tidy format. I'll write a solution if I find one !

**Comment by dgrtwo** [comment]
From that format, you could get to what you want using dplyr's `lead()`!

```
# (Use filter to remove the last word, which has no next)
corpus %>%
  mutate(next = lead(mots)) %>%
  filter(!is.na(next)) %>%
  mutate(ngram = paste(mots, next))
```

(You could also replace the `paste()` step with tidyr's `unite` if you want to get rid of the two word columns at the same time)

**Comment by Malichot** [comment]
Thanks a lot for your response ! I encounter an error nonetheless that tells me : 

``` r
Error in filter(!is.na(next)) : 
"no loop to break from (break / next), jumping to top level"
```

**Comment by dgrtwo** [comment]
Oops! I shouldn't have named the column `next`, which is a reserved word in R. Name it `next_word` instead (or the French equivalent!) I also should have used `lead` instead of `lag`, which teaches me to proofcheck my code more carefully...

```
corpus %>%
  mutate(next_word = lead(mots)) %>%
  filter(!is.na(next_word)) %>%
  mutate(ngram = paste(mots, next_word))
```

**Comment by Malichot** [comment]
Wow it works wonderfully !! My sincere thanks to you David !

**Comment by Malichot** [comment]
A small question remains (I don't want to take advantage of your kindness) : what if we want 3-grams or 5-grams - or _n_-grams ?

**Comment by dgrtwo** [comment]
For 3 grams, use the second argument to `lead()`, which says how many it's leading by:

```
corpus %>%
  mutate(next_word = lead(mots),
         next_word2 = lead(mots, 2)) %>%
  filter(!is.na(next_word), !is.na(next_word2)) %>%
  mutate(ngram = paste(mots, next_word, next_word2))
```

Once `n` gets too large this does get a little unwieldy. At that point, one solid option is the new (but on CRAN) slider package, which provides purrr-like functions that slide across rolling windows. I think this may be computationally slower than other approaches we could come up with, but if your data isn't huge it won't be a problem.

```
library(slider)

# Creating 5-grams means setting .after to 4 and removing last 4 rows
corpus %>%
  mutate(ngram = slide_chr(mots, paste, collapse = " ", .after = 4)) %>%
  head(-4)
```

**Comment by Malichot** [comment]
Too good !! Thanks again for your time ! :1st_place_medal:
