### ISSUE TITLE
Ngram tokenizer with NAs

### ISSUE THREAD

**Issue by clemens-zauchner** [juliasilge/tidytext#167]
When looking for bigrams in a `data.frame` column using `unnest_tokens` (or `unnest_ngrams`) and you have `NA`s in that column, the result will also be `NA`, without a warning. For example:
```R
data.frame(comments=c("this is a test comment",
                      NA,
                      "this is another comment"),
           stringsAsFactors = FALSE) %>% 
           unnest_tokens(bigram, input=comments, token = "ngrams", n = 2)

  bigram
1   <NA>
```

However, if you remove `NA`s, it works as expected:

```R
data.frame(comments=c("this is a test comment",
                      NA,
                      "this is another comment"),
           stringsAsFactors = FALSE) %>% 
    #filter(!is.na(comments)) %>% 
    unnest_tokens(bigram, input=comments, token = "ngrams", n = 2)

             bigram
1           this is
1.1            is a
1.2          a test
1.3    test comment
1.4    comment this
1.5         this is
1.6      is another
1.7 another comment
```

I wonder if a warning or at least an info message would be appropriate here?

**Comment by juliasilge** [comment]
Thanks for the report @clemens-zauchner!

Looks like this weird behavior is happening because of the behavior around `collapse = TRUE`:

``` r
library(tidytext)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tibble(comments=c("this is a test comment",
                  NA,
                  "this is another comment")) %>% 
  unnest_tokens(bigram, input=comments, token = "ngrams", n = 2, collapse = FALSE)
#> # A tibble: 8 x 1
#>   bigram         
#>   <chr>          
#> 1 this is        
#> 2 is a           
#> 3 a test         
#> 4 test comment   
#> 5 <NA>           
#> 6 this is        
#> 7 is another     
#> 8 another comment
```

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll have to think about what `collapse = TRUE` *should* do with `NA` values, though... 🤔

**Comment by juliasilge** [comment]
I've been thinking about this a bit more, and I am becoming convinced that the behavior as it currently exists is the best option. Comparing the `collapse = TRUE` compared to `collapse = FALSE` behavior, it seems unclear or dangerous to me to make a different choice about handling the `NA` values in collapsing. This helps me see this more clearly:

``` r
library(stringr)
str_c("this is a test comment", NA, "this is another comment")
#> [1] NA
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The `unnest_tokens()` function currently does not have any kind of `na.rm` argument that could get passed on; I'm not sure that it would be less confusing than instead pointing folks to `collapse` and its `TRUE`/`FALSE` options.

**Comment by juliasilge** [comment]
I've taken some time to think through this more, and I do think the behavior is best as is. Users can use `collapse = FALSE` when appropriate, but otherwise I do think that the `NA` handling is best as is.

Thank you so much for your thoughtful feedback! 🙌
