### ISSUE TITLE
afinn url

### ISSUE THREAD

**Issue by eddyzhang2018** [juliasilge/tidytext#172]
Hi Julia,

it looks like the afin data url has changed:

if use lexicon_afin() will encounter following error:

>my_lex <- lexicon_afinn()

Do you want to download:
 Name: AFINN-111 
 URL: http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=6010 
 License: Open Database License (ODbL) v1.0 
 Size: 78 KB (cleaned 59 KB) 
 Download mechanism: https 

1: Yes
2: No

Selection: 1
trying URL 'https://www2.imm.dtu.dk/pubdb/views/edoc_download.php/6010/zip/imm6010.zip'
Warning in download.file(url = "https://www2.imm.dtu.dk/pubdb/views/edoc_download.php/6010/zip/imm6010.zip",  :
  cannot open URL 'https://www2.imm.dtu.dk/pubdb/views/edoc_download.php/6010/zip/imm6010.zip': HTTP status was '404 Not Found'
Error in download.file(url = "https://www2.imm.dtu.dk/pubdb/views/edoc_download.php/6010/zip/imm6010.zip",  : 
  cannot open URL 'https://www2.imm.dtu.dk/pubdb/views/edoc_download.php/6010/zip/imm6010.zip'`

they move the website to http://www2.imm.dtu.dk/pubdb/pubs/6010-full.html, so the downloading now host at http://www2.imm.dtu.dk/pubdb/edoc/imm6010.zip. 

Any chance to update the url in this function?

Thank you.

**Comment by EmilHvitfeldt** [comment]
This issue originate in [textdata](https://github.com/EmilHvitfeldt/textdata) and have been fixed.
Related to https://github.com/EmilHvitfeldt/textdata/issues/31.

You can download the version with

```r
remotes::install_github("EmilHvitfeldt/textdata")
```
<img width="636" alt="Screen Shot 2020-05-03 at 10 21 30 AM" src="https://user-images.githubusercontent.com/14034784/80920966-13e1e100-8d28-11ea-821f-0cdb683d59f2.png">

**Comment by juliasilge** [comment]
Thank you so much @EmilHvitfeldt for your quick handling of the underlying problem! 🙏

**Comment by ThanhDatIU** [comment]
Hello @juliasilge,

I got the same problem even when using lexicon_afinn() running in DataCamp workspace with the latest version 4.1.2.

<img width="709" alt="Screen Shot 2022-01-30 at 12 08 25 pm" src="https://user-images.githubusercontent.com/56287595/151687511-39dd8a69-ff35-4517-a2b6-fa756737caa5.png">

Any chance to update the URL in this function?

Thank you.

**Comment by juliasilge** [comment]
@ThanhDatIU The function works with the current CRAN version of textdata (0.4.1) so I believe we are all good to go with that.
