### ISSUE TITLE
tbl_df deprecated warning

### ISSUE THREAD

**Issue by reblake** [juliasilge/tidytext#178]
Using the tidy() function on a corpus object results in a deprecated warning for tbl_df. 
```
Warning message:
`tbl_df()` is deprecated as of dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.
```

**Comment by juliasilge** [comment]
This was fixed in a483da389a8f3fdfe6354320ba49e99d9251b13e. 👍 

You can get the updated version of tidytext via:

```r
devtools::install_github("juliasilge/tidytext")
```

**Comment by reblake** [comment]
When will this be fixed on CRAN?  I can only load packages from CRAN in the platform I'm using to teach text analysis.

**Comment by juliasilge** [comment]
I would estimate within the next month or so. In the meantime, nothing bad is actually happening with this warning so no worries about the actual computation.
