### ISSUE TITLE
a few deprecated functions

### ISSUE THREAD

**Issue by wordsmith189** [juliasilge/tidytext#179]
Trying to implement the word pairs example (section 4.2.1 in _Text Mining with R_) I came across a couple of warnings about deprecated functions called under the hood: 

```
`distinct_()` is deprecated as of dplyr 0.7.0.
Please use `distinct()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.`tbl_df()` is deprecated as of dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
```

**Comment by juliasilge** [comment]
These have been addressed in the current development version of tidytext:

```r
devtools::install_github("juliasilge/tidytext")
```

I'll do a CRAN release pretty soon as well but in the meantime nothing harmful is going on.

**Comment by juliasilge** [comment]
A new version of [tidytext is on CRAN as of today](https://cran.r-project.org/package=tidytext) and the binaries should be built soon.

**Comment by wordsmith189** [comment]
Fantastic! Thank you so much for this package.
