### ISSUE TITLE
unnest_tokens keep groups unchanged

### ISSUE THREAD

**Issue by moodymudskipper** [juliasilge/tidytext#184]
After calling unnest_tokens, groups should be either dropped or adapted, currently they stay as they were before the transformation.

Here's an example : 

``` r
library(tidytext)
library(dplyr, warn.conflicts = FALSE)
library(janeaustenr)

d <- 
  tibble(txt = prideprejudice) %>%
  mutate(group = rep(1:2, nrow(.)/2)) %>%
  group_by(group)

res <- d %>%
  unnest_tokens(word, txt)

# groupattribute is not updated 
nrow(d)
#> [1] 13030
nrow(res)
#> [1] 122204
attr(d, "groups")
#> # A tibble: 2 x 2
#>   group       .rows
#> * <int> <list<int>>
#> 1     1     [6,515]
#> 2     2     [6,515]
attr(res, "groups")
#> # A tibble: 2 x 2
#>   group       .rows
#> * <int> <list<int>>
#> 1     1     [6,515]
#> 2     2     [6,515]

# cryptic error messages ensue
res %>% arrange(word)
#> Warning in NextMethod(): le nombre d'objets à remplacer n'est pas multiple de la
#> taille du remplacement
#> # A tibble: 122,204 x 2
#> # Groups:   group [2]
#>    group word        
#>    <int> <chr>       
#>  1     2 _accident_  
#>  2     2 _advantages_
#>  3     2 _affect_    
#>  4     1 _all_       
#>  5     1 _all_       
#>  6     1 _all_       
#>  7     2 _all_       
#>  8     1 _am_        
#>  9     2 _another    
#> 10     2 _any_       
#> # ... with 122,194 more rows
```

<sup>Created on 2020-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Very strangely, while the above is straight out of reprex and triggers a warning, when ran in a clean session it returns an error on my system, but this is probably not directly related to the issue here.

I encountered it as I had wrongly assumed/remembered that `unnest_tokens` would keep the grouping columns and the unnested column only, similar to what `summarize(d, word = unlist(strsplit(txt, "\\b")))` would do.

Thanks for the great work.

**Comment by juliasilge** [comment]
I believe this is a new warning from recent-ish changes in dplyr, but I looked at this in some detail and there is some thinking/work to do around how `unnest_tokens()` should treat grouped data. Originally, our intention was for this function to basically ignore but preserve groups but:

- I'm not sure if that makes sense now
- it is not implemented well if we do want to support grouped data input

Right now, grouped data is handled much better when `collapse = TRUE`, for example with `token = "sentences"`:

``` r
library(tidytext)
library(tidyverse)
library(janeaustenr)

dat <- 
  tibble(txt = prideprejudice) %>%
  mutate(group = rep(1:2, nrow(.)/2)) %>%
  group_by(group)

res <- dat %>%
  unnest_tokens(word, txt, token = "sentences")

res %>% arrange(word)
#> # A tibble: 6,809 x 2
#> # Groups:   group [2]
#>    group word                                                                   
#>    <int> <chr>                                                                  
#>  1     1 "_he_ shall be  to think ill of a young man who has lived so long in d…
#>  2     1 "_he_ was exactly what he had been, when i satisfied with her behaviou…
#>  3     2 "_her_ mind little information, and uncertain temper."                 
#>  4     2 "_his_ eyes had been soon and repeatedly turned while, shared the feel…
#>  5     1 "_my_ appears to do so much credit to--but he gave up everything to be…
#>  6     2 "_my_ me on this subject for ever.\""                                  
#>  7     2 "_she_ will not be able to help calling.\""                            
#>  8     1 "_that_ abominable mr."                                                
#>  9     1 "_that_ important, and never open their mouths, quite mistake the matt…
#> 10     2 "_that_ is all to be forgot."                                          
#> # … with 6,799 more rows
```

<sup>Created on 2020-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The collapsing does not happen across groups, and the groups are correctly reattached. (But if you were to use `drop = FALSE` with this, you would probably not get what you expect.)

One option to consider is that it was a mistake to ever try to handle the grouped data case, because it is ambiguous what users want to happen. Instead we have the `collapse` option, which handles this related idea of how to combine text across observations, and of course folks can `nest()` their data in any arbitrary way and use `map()`. We could think about eventually erroring (start with a warning) when the input is grouped.

**Comment by juliasilge** [comment]
Well, I thought through this, reflected on the feedback we've gotten on grouped data and the `collapse` argument over the years, and chatted with folks about this; in the end, I decided this was the time to try out a more major change to address this problem; you can get this change by installing:

```r
devtools::install_github("juliasilge/tidytext")
``` 

You can read [more details here](https://juliasilge.com/blog/tidytext-collapse-change/) but the main points are:

- the handling of the `collapse` argument has changed (now `NULL` or a character vector)
- grouped data can also specify collapsing variables (this doesn't really affect the single word case)

The results on your example:

``` r
library(tidytext)
library(dplyr, warn.conflicts = FALSE)
library(janeaustenr)

d <- 
  tibble(txt = prideprejudice) %>%
  mutate(group = rep(1:2, nrow(.)/2)) %>%
  group_by(group)

res <- d %>%
  unnest_tokens(word, txt)

nrow(d)
#> [1] 13030
nrow(res)
#> [1] 122204
group_data(d)
#> # A tibble: 2 x 2
#>   group       .rows
#> * <int> <list<int>>
#> 1     1     [6,515]
#> 2     2     [6,515]
group_data(res)
#> # A tibble: 2 x 2
#>   group       .rows
#> * <int> <list<int>>
#> 1     1    [60,758]
#> 2     2    [61,446]
res %>% arrange(word)
#> # A tibble: 122,204 x 2
#> # Groups:   group [2]
#>    group word        
#>    <int> <chr>       
#>  1     2 _accident_  
#>  2     2 _advantages_
#>  3     2 _affect_    
#>  4     1 _all_       
#>  5     1 _all_       
#>  6     1 _all_       
#>  7     2 _all_       
#>  8     1 _am_        
#>  9     2 _another    
#> 10     2 _any_       
#> # … with 122,194 more rows
```

<sup>Created on 2020-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

If you are on the risk tolerant side and willing to install from GitHub, feedback would be welcome!

**Comment by moodymudskipper** [comment]
Thanks Julia, this looks good.

As far as I'm concerned, I wouldn't use groups as another way to set `collapse`, because : 
* It means there's two ways to do it when either is easy enough
* These groups don't have exactly the same meaning as what we find in the tidyverse, no other group handling function looks at runs (adjacent values in your text).

I believe Hadley tried to use groups in ggplot2, to set implicitly a group aesthetics, but the experience wasn't successful, I believe for the reasons above.

`tidyr::separate_rows` and `tidyr::unnest` recompute the groups, and the computations ignore the groups, I think I would expect `unnest_token` to work the same way.

I'm sure you'll choose what makes sense, thanks again.
