### ISSUE TITLE
get_lexicon(nrc) error

### ISSUE THREAD

**Issue by M4rk3h** [juliasilge/tidytext#189]
When using the nrc lexicon, i'm prompted to cite the lexicon if used, when pressing yes, I get an error.

> Error: '/home/mark/.cache/textdata/nrc/NRC-Emotion-Lexicon/NRC-Emotion-Lexicon-v0.92/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt' does not exist.

Using an Ubuntu based os, thanks.

EDIT: All other lexicon dictionaries work fine.

**Comment by EmilHvitfeldt** [comment]
This appears to be a `textdata` issue. Try running

```r
textdata::lexicon_nrc(delete=TRUE)
```

and then

```r
textdata::lexicon_nrc()
```

to redownload the lexicon.

**Comment by M4rk3h** [comment]
Thanks for the quick reply, 

(I didn't realize it was the `textdata` package, i'm new to R).

This solved the issue.
