### ISSUE TITLE
Converting from STM (textProcessor) object to a tidy object (or other workaround)?

### ISSUE THREAD

**Issue by sarseo1** [juliasilge/tidytext#190]
Hi Julia,

Long time lurker, first time poster. I've been working with the tidyverse for a few years now and absolutely love it. However, I've been having some problems and hope you can help me out.

To prep for structural topic modeling, I've cleaned my text data using the `tm` package then convert to a tidy matrix. I then create an STM object using the `textProcessor` to reduce sparsity to 98.5%. I now want to convert the STM object into a tidy object to calculate some basic descriptive statistics but cannot seem to find any way to convert it.

Do you have any thoughts on how I can convert the `textProcessor` object to a tidy object to calculate those stats? if not, do you have any thoughts on how I can reduce the sparsity either when converting from my `VCorpus` object to tidy or in my tidy object to properly calculate my descriptive stats? Hopefully the code I provide below provides some sense of where I am. Thanks in advance!

```
docs.td <- tidy(docs.c)
meta.df <- data.frame(docs.td$id, docs.td$year, 
                      docs.td$upcprop, docs.td$elprop, docs.td$frplprop,
                      docs.td$blackprop, docs.td$othprop, docs.td$hispprop,
                      docs.td$whiteprop, docs.td$blau, 
                      docs.td$highneed, 
                      docs.td$enroll, docs.td$meanexp, docs.td$meanyrsteach, 
                      docs.td$pto,
                      docs.td$county, docs.td$locale, docs.td$anypto, docs.td$sizecat,
                      stringsAsFactors = FALSE)

library(stm) # I have decided to go with .985 sparse level (term must exist in at least 1.5% of all docs)
stm.dtm <- textProcessor(documents = docs.td$text, metadata = meta.df,
                         lowercase = FALSE, removestopwords = FALSE,
                         removenumbers = FALSE, removepunctuation = TRUE,
                         stem = FALSE, sparselevel = .985, language = "en", verbose = T)

out <- prepDocuments(stm.dtm$documents, stm.dtm$vocab, stm.dtm$meta, verbose = T)  
documents <- out$documents
vocab <- out$vocab
meta <- out$meta
```

**Comment by juliasilge** [comment]
I think I would not bother with converting back and forth to a different kind of object and instead do the filtering to reduce sparsity, i.e. filter out rarely used used, directly using dplyr verbs. You can first `group()` by your term/word/token variable and then `filter()` to keep only the term you want in the dataset. You could do this by counts, or the way you talked about here, by proportion:
``` r
library(tm)
#> Loading required package: NLP
library(tidytext)
library(tidyverse)

data("AssociatedPress", package = "topicmodels")
ap_td <- tidy(AssociatedPress)
ap_td
#> # A tibble: 302,031 x 3
#>    document term       count
#>       <int> <chr>      <dbl>
#>  1        1 adding         1
#>  2        1 adult          2
#>  3        1 ago            1
#>  4        1 alcohol        1
#>  5        1 allegedly      1
#>  6        1 allen          1
#>  7        1 apparently     2
#>  8        1 appeared       1
#>  9        1 arrested       1
#> 10        1 assault        1
#> # … with 302,021 more rows

## term must exist in at least 1.5% of all docs
ap_td %>%
  group_by(term) %>%
  filter(n_distinct(document) / n_distinct(ap_td$document) >= 0.015) %>%
  ungroup()
#> # A tibble: 209,167 x 3
#>    document term        count
#>       <int> <chr>       <dbl>
#>  1        1 adding          1
#>  2        1 ago             1
#>  3        1 allegedly       1
#>  4        1 apparently      2
#>  5        1 appeared        1
#>  6        1 arrested        1
#>  7        1 assault         1
#>  8        1 atlantic        2
#>  9        1 attempted       1
#> 10        1 authorities     1
#> # … with 209,157 more rows
```

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

You can then take this tidy dataset from here and calculate descriptive stats, and then do whatever other kind of analysis you need, like [topic modeling with stm after converting to a sparse matrix](https://juliasilge.com/blog/evaluating-stm/).

**Comment by sarseo1** [comment]
Thank you so much for your quick reply, Julia - I really appreciate it. Your suggestion to reconstruct the sparsity levels using `filter` is a great solution. I'm having a little trouble understanding exactly what the different uses of `n_distinct` are doing in your code, though. I'm going to keep working with it and will hopefully get where I need to calculate my stats.

Again, thanks so much for all your work building user-friendly packages, textbooks, etc. I'm well on my way to converting many in my department to the fellow `tidyverse` travelers. 

Best wishes!

**Comment by juliasilge** [comment]
Here is another version that is a little more explicit about what `n_distinct()` is doing:

``` r
library(tm)
#> Loading required package: NLP
library(tidytext)
library(tidyverse)

data("AssociatedPress", package = "topicmodels")
ap_td <- tidy(AssociatedPress)
ap_td
#> # A tibble: 302,031 x 3
#>    document term       count
#>       <int> <chr>      <dbl>
#>  1        1 adding         1
#>  2        1 adult          2
#>  3        1 ago            1
#>  4        1 alcohol        1
#>  5        1 allegedly      1
#>  6        1 allen          1
#>  7        1 apparently     2
#>  8        1 appeared       1
#>  9        1 arrested       1
#> 10        1 assault        1
#> # … with 302,021 more rows

ap_td %>%
  mutate(total_docs = n_distinct(ap_td$document)) %>%
  group_by(term) %>%
  mutate(term_docs = n_distinct(document),
         term_prop = term_docs / total_docs) %>%
  filter(term_prop >= 0.015) %>%
  ungroup()
#> # A tibble: 209,167 x 6
#>    document term        count total_docs term_docs term_prop
#>       <int> <chr>       <dbl>      <int>     <int>     <dbl>
#>  1        1 adding          1       2246        66    0.0294
#>  2        1 ago             1       2246       327    0.146 
#>  3        1 allegedly       1       2246        52    0.0232
#>  4        1 apparently      2       2246       105    0.0467
#>  5        1 appeared        1       2246       138    0.0614
#>  6        1 arrested        1       2246       140    0.0623
#>  7        1 assault         1       2246        46    0.0205
#>  8        1 atlantic        2       2246        44    0.0196
#>  9        1 attempted       1       2246        36    0.0160
#> 10        1 authorities     1       2246       238    0.106 
#> # … with 209,157 more rows
```

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Thank you so much for the kind words, and best of luck! 🙌
