### ISSUE TITLE
Failure to install.package

### ISSUE THREAD

**Issue by lucas-dopaes** [juliasilge/tidytext#191]
Dear Julia,

I've studied this package and this seems fantastic. Thank you for this!

I'm trying to install the package and learn more about it but I'm facing some problems, as 
`> install.packages("tidytext")
Installing package into ‘C:/Users/lucas/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
         binary source needs_compilation
tidytext  0.2.4  0.3.0             FALSE

installing the source package ‘tidytext’

trying URL 'https://cran.rstudio.com/src/contrib/tidytext_0.3.0.tar.gz'
Content type 'application/x-gzip' length 3022614 bytes (2.9 MB)
downloaded 2.9 MB

* installing *source* package 'tidytext' ...
** package 'tidytext' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error : object 'vec_rep_each' is not exported by 'namespace:vctrs'
ERROR: lazy loading failed for package 'tidytext'
* removing 'C:/Users/lucas/Documents/R/win-library/3.5/tidytext'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘tidytext’ had non-zero exit status`

**Comment by juliasilge** [comment]
Hmmm, that's strange! It looks like you have an older version of vctrs installed but it did not update. You might be able to solve this by running:

```r
update.packages()
```
and then installing, or by forcing:

```r
install.packages("vctrs")
```
and then installing tidytext.

**Comment by lucas-dopaes** [comment]
Many thanks, Julia! It worked!

**Comment by juliasilge** [comment]
Glad to hear that! 🙌
