### ISSUE TITLE
Support conf.int argument in `tidy()` function

### ISSUE THREAD

**Issue by jooyoungseo** [juliasilge/tidytext#194]
Currently, `tidytext::tidy()` does not support `conf.int` option for `estimateEffect` object. It would be great if it could be added.

## Reprex

``` r
library(stm)
#> stm v1.3.6 successfully loaded. See ?stm for help. 
#>  Papers, resources, and other materials at structuraltopicmodel.com
library(tidytext)

prep <- estimateEffect(c(1) ~ treatment, gadarianFit, gadarian)
tidy(prep, conf.int = TRUE)
#> # A tibble: 2 x 6
#>   topic term        estimate std.error statistic  p.value
#>   <int> <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1     1 (Intercept)    0.437    0.0206     21.2  3.75e-64
#> 2     1 treatment     -0.150    0.0309     -4.86 1.77e- 6
```

<sup>Created on 2021-05-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jooyoungseo** [comment]
I also was wondering if this could be integrated into `broom::tidy()` and `tidytext::tidy()` use that as a wrapper function. Just thought.

**Comment by juliasilge** [comment]
The reason that tidytext doesn't support a `conf.int` option for this model is that there isn't a `confint.estimateEffect` method from the stm package. You can see how the [`broom:::broom_confint_terms()` function for `lm()` type models works here](https://github.com/tidymodels/broom/blob/master/R/utilities.R), and notice that stm doesn't have the [needed `confint` method for `estimateEffect`](https://github.com/bstewart/stm/blob/master/R/estimateEffect.R). You could ask the maintainer Brandon what he thinks about this and if it makes sense to support that functionality.

**Comment by juliasilge** [comment]
And broom is always looking to support _fewer_ models, not more (it is so unwieldy as is), so it makes more sense to keep the text-specific model tidiers here in tidytext.

**Comment by juliasilge** [comment]
Let me know if you get any further info on a `confint` method from the stm package! 🙌
