### ISSUE TITLE
Rename stopwords to stop_words?

### ISSUE THREAD

**Issue by dgrtwo** [juliasilge/tidytext#2]
If either tm or quanteda is loaded after tidytext, their `stopwords` function can replace our dataset. In any case it means the same name appears across three text-mining packages.

Should we rename the stopwords dataset to stop_words to avoid this?

**Comment by juliasilge** [comment]
Yessssssssss... Excellent idea.

**Comment by dgrtwo** [comment]
Awesome, I'm on it. Incidentally I discovered there's a recommended practice for our raw data [described here](http://r-pkgs.had.co.nz/data.html#data-extdata): I'll implement that in the same commit.

Just added tm::Corpus and quanteda::corpus tidiers + vignette examples for them, btw

**Comment by dgrtwo** [comment]
Closed in 9edc2b90e5223d468f994878b73dd8173c23c3a2
