### ISSUE TITLE
unnest_tokens(token = "tweets") not separating consecutive unicodes (emojis)

### ISSUE THREAD

**Issue by PursuitOfDataScience** [juliasilge/tidytext#203]
Hi Julia,
I've been using `tidytext` to analyze tweet corpus and following along the Chapter 7 ([link](https://www.tidytextmining.com/twitter.html)) of Text Mining with R about the tweet case study. A few issues I've encountered along the way, and I have done my homework to try to address them. Alas, I am not able to and here I initiate the issue and hope you can help me out.

I do notice that when you print tweet words after using `unnest_token()`, the actual emojis will appear, like the screenshot I have below:
![image](https://user-images.githubusercontent.com/54338793/149965808-d19273ba-7214-4b7d-ba87-eaa71e250d55.png).

Yet, when I `View()` or `print()` tweet words for my own analysis, it is just some non-sense unicodes without being properly rendered (see below). I think it might be a Windows system issue, or something else. I use the latest R and RStudio, which shouldn't be anything of version.

![image](https://user-images.githubusercontent.com/54338793/149966015-20564bbd-6df9-4471-9f92-a374b0918957.png)

Another issue you can see from my above screenshot is `unnest_tokens()` does not separate consecutive unicodes. I tried to use `str_remove()`, `separate_rows()` and other functions I can think of to do so, but none of them worked. When I make a plot for the words, you can see the word `bye` is attached with two emojis in a row. I am wondering if you have any good ways to separate them so that each emoji/word is on its unique row. And the emojis are also black/white when they show up on the plot rather than their original rendering. Thanks for your help!

![image](https://user-images.githubusercontent.com/54338793/149966962-48efcc17-07a4-42b4-a6c6-371be86b7223.png)

**Comment by juliasilge** [comment]
For your first question about rendering emoji in the RStudio IDE, I believe that this is intended. The IDE team has worked on how emoji are rendered in the console and in documents, but when you use the [data viewer](https://support.rstudio.com/hc/en-us/articles/205175388-Using-the-Data-Viewer-in-the-RStudio-IDE#restrictions-and-performance) the underlying data is displayed. You can [look through issues on the IDE repo](https://github.com/rstudio/rstudio/issues?q=is%3Aissue+emoji) to see if folks have reported this and/or the team has addressed this.

For your second issue, this depends on how tokenizers and especially stringi behaves. Check out [this issue](https://github.com/ropensci/tokenizers/issues/68) and this PR, and try out what they suggest about `strip_punct`:

``` r
txt <- c("Hello \U0001f64c\U0001f3ff\U0001f4e6", "Hello \U0001f64c\U0001f4e6")
tokenizers::tokenize_tweets(txt, strip_punct = TRUE)
#> [[1]]
#> [1] "hello"  "🙌🏿📦"
#> 
#> [[2]]
#> [1] "hello" "🙌📦"
tokenizers::tokenize_tweets(txt, strip_punct = FALSE)
#> [[1]]
#> [1] "hello" "🙌🏿"  "📦"   
#> 
#> [[2]]
#> [1] "hello" "🙌"    "📦"
```

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

You can pass `strip_punct` through the dots of `unnest_tokens()`, as [laid out in the docs](https://juliasilge.github.io/tidytext/reference/unnest_tokens.html#arguments-1).

On your last issue about using ggplot2, there are a couple of options. You can [change your graphics device to use ragg](https://www.tidyverse.org/blog/2021/02/modern-text-features/#color-fonts), or check out [alternative approaches](https://www.emilhvitfeldt.com/post/2020-01-02-real-emojis-in-ggplot2/).

**Comment by PursuitOfDataScience** [comment]
Thank you so much for your help!
