### ISSUE TITLE
reorder_within() does not work as it should with scale_x/y_log10()

### ISSUE THREAD

**Issue by PursuitOfDataScience** [juliasilge/tidytext#204]
Hi,

I have used `reorder_within()` for numerous times and never encountered an issue. This one just came out of the blue. I found out that there is some problem when working `reorder_within()` in conjunction with `scale_x_log10()`. Here is an example to flesh out the issue:

```
read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/country_totals.csv') %>%
  select(-level) %>%
  mutate(country_name = if_else(is.na(country_name), country, country_name)) %>%
  pivot_longer(c(`2016`:`2018`), names_to = "year") %>%
  filter(value > 0) %>%
  mutate(country_name = reorder_within(country_name, value, year, sum, na.rm = T)) %>%
  ggplot(aes(value, country_name, fill = type)) +
  geom_col() +
  scale_x_log10() + ## this is where the issue is. When this line gets commented, reorder_within() should work
  scale_y_reordered() +
  facet_wrap(~year, scales = "free_y") 
```

When I comment out `scale_x_log10()`, it produces the following plot, which is perfectly reordered:

![image](https://user-images.githubusercontent.com/54338793/151083036-e5855537-48bb-48ce-b08b-9ac85e1b9ca4.png)

But when I include the line, the plot looks like this:

![image](https://user-images.githubusercontent.com/54338793/151083129-8d02b3ec-d9ac-4bae-bbdb-372d3a67a951.png)

Any ideas on what went wrong here? I guess there is a scaling issue, but I am not sure. Hope you can shed some light on it. Thanks!

**Comment by juliasilge** [comment]
If you want to order by the log, I think you need to say that specifically:

``` r
library(tidyverse)
library(tidytext)

df <- 
  read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/country_totals.csv') %>%
  select(-level) %>%
  mutate(country_name = if_else(is.na(country_name), country, country_name)) %>%
  pivot_longer(c(`2016`:`2018`), names_to = "year") %>%
  filter(value > 0) 
#> Rows: 185 Columns: 7
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (4): country, country_name, type, level
#> dbl (3): 2016, 2017, 2018
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

df %>%
  mutate(country_name = reorder_within(country_name, log10(value), year, sum, na.rm = T)) %>%
  ggplot(aes(value, country_name, fill = type)) +
  geom_col() +
  scale_x_log10() +
  scale_y_reordered() +
  facet_wrap(vars(year), scales = "free_y") 
```

![logscale](https://user-images.githubusercontent.com/12505835/151241132-d5f96862-c3b8-405f-a6b4-79242f3c4efe.png)

<sup>Created on 2022-01-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The ordering got a little complicated because you have multiple rows for each country but you don't have _every_ `type` for each country.

**Comment by PursuitOfDataScience** [comment]
Thanks for the help.
