### ISSUE TITLE
gen_sentiments("nrc")  fails due to change in url 

### ISSUE THREAD

**Issue by rfaridi** [juliasilge/tidytext#211]
The download url changed from 'http://saifmohammad.com/WebDocs/NRC-Emotion-Lexicon.zip'   to 'http://saifmohammad.com/WebDocs/Lexicons/NRC-Emotion-Lexicon.zip'.   I have wasted couple of hours to find the glitch. Interim solution is to manually download the file, put it in the return_file directory and then run lexicon_nrc(manual_download=T).

**Comment by EmilHvitfeldt** [comment]
Hello @rfaridi 👋 

This should be fixed now in {textdata} version 0.4.2. You can get it by using `install.package("textdata")` in a little bit (still waiting for CRAN to build.
If you need it now you can install it with

```r
# install.packages("remotes")
remotes::install_github("emilhvitfeldt/textdata@v0.4.2")
```

**Comment by rfaridi** [comment]
Great! Thanks a lot for quick response!

**Comment by juliasilge** [comment]
Thank you so much @EmilHvitfeldt! 🙌
