### ISSUE TITLE
Named Entity Recognition and POS

### ISSUE THREAD

**Issue by nabsiddiqui** [juliasilge/tidytext#213]
Is there a desire to include Named Entity Recognition and POS tagging? I have been using spacyr and udpipe with fairly simple commands to get these results. However, these require downloading models, etc. and could be streamlined or packaged with tidytext. You can get the results in a tidy framework by doing the following in spacyr:

```
spacy_initialize(model = "en_core_web_sm")
text_df_with_tags <- text_df %>%
  mutate(spacy_parse(word)) %>%
  select(-doc_id, -sentence_id, -token_id, -token) 
```

The same can also be done with udpipe:

```
model <- udpipe_download_model(language = "english")
english_model <- udpipe_load_model(model$file_model)

text_df_with_tags <- text_df %>%
  mutate(as.data.frame(udpipe_annotate(english_model, word))) %>%
  select(-doc_id, -sentence_id, -token_id, -token)
```

Udpipe runs locally and could be packaged with tidytext. A function, such as `get_tags()` could return all the results and have the user filter or there can be different functions for different tags. Some don't make sense in the tidytext format. Don't know if there is a desire to do something like this or if it is better to run it the way it is.

**Comment by nabsiddiqui** [comment]
Just realized that there is actually a POS option, but there is no tutorial on how to use it. I am assuming it is just an inner join? Either way, this can stay open if there is a desire to get Named Entity Recognition, etc.

**Comment by juliasilge** [comment]
If you are interested in a tidy data interface for POS and friends, I recommend the cleanNLP package:
https://statsmaths.github.io/cleanNLP/

**Comment by nabsiddiqui** [comment]
Thank you. I think the left join with parts of speech should work sufficiently for my case. I will use the suggested package when needed. 

Going to go ahead and close this.
