### ISSUE TITLE
Make hunspell a Suggested dependency?

### ISSUE THREAD

**Issue by MichaelChirico** [juliasilge/tidytext#220]
Currently `tidytext` only uses `hunspell` to tokenize non-default formats in `unnest_tokens()`:

https://github.com/juliasilge/tidytext/blob/03aabd03378cbdb5999902f8a65be6c47298ec12/R/unnest_tokens.R#L51-L53

https://github.com/juliasilge/tidytext/blob/03aabd03378cbdb5999902f8a65be6c47298ec12/R/unnest_tokens.R#L200-L201

It would be easy enough to block that usage behind a `requireNamespace()` check and thereby demote `tidytext` to a `Suggests:` dependency.

**Comment by juliasilge** [comment]
Sounds like a good plan! 🙌
