### ISSUE TITLE
Weighted Term Frequency

### ISSUE THREAD

**Issue by eliasdabbas** [juliasilge/tidytext#23]
Thanks a lot for the package and the book, really enjoying them.

My recommendation here does not require any new features or coding, but simply demonstrating a powerful way to use `unnest_tokens()` in a special case, when documents in a corpus come each with a certain metric. 

A simple example to illustrate my point. Assume we have a report for a set of keywords (the documents) with the impressions each generated:

``` r
library(tibble)
news_keywords <- data_frame(
  keyword = c("us news", "us elections", "china news", "china updates", "latest china news", "china newspaper"),
  impressions = c(500, 500, 100, 100, 100, 100)
)
news_keywords


#>  A tibble: 6 × 2
#>             keyword  impressions
#>                <chr>       <dbl>
#> 1           us news         500
#> 2      us elections         500
#> 3        china news         100
#> 4     china updates         100
#> 5 latest china news         100
#> 6   china newspaper         100
```

Now we separate the words with `tidytext::unnest_tokens()`

``` r
library(tidytext)
library(magrittr)
news_words <- news_keywords %>% 
  unnest_tokens(output = words, input = keyword) 
```

Counting the frequency

``` r
library(dplyr)  
news_words %>% count(words, sort = TRUE)
#>  A tibble: 7 × 2
#>       words     n
#>       <chr> <int>
#> 1     china     4
#> 2      news     3
#> 3        us     2
#> 4 elections     1
#> 5    latest     1
#> 6 newspaper     1
#> 7   updates     1
```

We can see that the most frequently used words are "china", "news", then "us".   

Now let's take a look at the weighted frequency

``` r
news_words %>%   
  group_by(words) %>%   
  summarise(impressions = sum(impressions)) %>%   
  arrange(desc(impressions))

#>  A tibble: 7 × 2
#>        words impressions
#>        <chr>       <dbl>
#> 1        us        1000
#> 2      news         700
#> 3 elections         500
#> 4     china         400
#> 5    latest         100
#> 6 newspaper         100
#> 7   updates         100
```

Here, we see a completely different view, where "us" is the most frequent (by number of impressions) and china is in fourth position.  
While "china" occurs more often in the keywords, there are more times that people search for keywords that include "us", and therefore "us" is bigger in terms of searches.

Another simple example: let's say the most frequent word you use in your tweets is "dplyr", but when you take into consideration the number of impressions of your tweets, you might find that tweets that generated the most impressions where the ones with "ggplot" in them. 
### Possible use cases:

| Text | Metrics |
| --- | --- |
| search engine keywords | impressions, clicks, conversions |
| tweet text | impressions, engagements, retweets |
| web page titles | pageviews, avg. session duration |
| song\* / movie / book title | downloads, sales, likes |

If you think this is useful, I'd be more than happy to expand, and share more detailed examples. 

'\* might work with your post  https://www.washingtonpost.com/news/wonk/wp/2016/10/01/the-states-that-americans-sing-about-most/?postshare=5471475343908445&tid=ss_tw

**Comment by juliasilge** [comment]
I meant to comment on this earlier; thanks so much for sharing this work!

This type of weighting is an interesting analogy to tf-idf; term frequency on its own can be useful in some contexts, but sometimes we need to weight it by some other metric (like idf, or in this case, something like, say, impressions or clicks).

**Comment by juliasilge** [comment]
Thanks again for sharing this! We are getting ready for a CRAN release soon so I am clearing out issues that we need to deal with and am going to close this. I really like your ideas here; this weighting is similar in spirit to some of the analyses we do in our book, like looking at [words that lead to retweets/favorites on Twitter](http://tidytextmining.com/twitter.html).
