### ISSUE TITLE
Replacement of `token = "tweets"` 

### ISSUE THREAD

**Issue by NajaMLindelof** [juliasilge/tidytext#232]
Hello!

Firstly, thanks a lot for creating and maintaining this package! It is really great to work with.

I have been using the `token = "tweets"` Twitter tokenizer quite a lot - do you have a recommended replacement of its function (mainly retaining hasthtags, usernames, URLs etc) after its #227 tidytext 0.4.0 removal?

Thanks a lot!

**Comment by juliasilge** [comment]
I would go back to using a regular expression with `token = "regex"`, which is what we did before the `token = "tweets"` option was available. Take a look [at this change in our book](https://github.com/dgrtwo/tidy-text-mining/commit/e9b98a1384bdec106a8ba3d2fe94f03a1c43b636), where we replaced a regex with `token = "tweets"`, and make the opposite change where you go back to using the regular expression.

**Comment by NajaMLindelof** [comment]
Brilliant, thanks!
