### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by MansMeg** [juliasilge/tidytext#24]
Hi Julia!

I totally love your package and way to handle text data. Im working with topic models and was thinking of trying to start with a tidytopic package for topic models using the same format. Is tidytext stabile enough to build upon, you would say? Do you have any suggestions on API to enable additional packages?

You can reach me on mons.magnusson at gmail dot com if you want to discuss more in details.

**Comment by dgrtwo** [comment]
Thanks for the feedback Mans! Note that tidytext already supports tidying topic models from the LDA package- [see this chapter](http://tidytextmining.com/topicmodeling.html) for more.

Were you interested in tidying topic models from another package besides LDA? If so, I think it would be a good pull request for the tidytext package, at which point we could add it in. Modeling your approach off of the tidy.LDA method seen in that chapter would be a good idea (the more similar the output, the easier it will be to share examples or to compare results).

**Comment by MansMeg** [comment]
Sure. I'm now working both with the rmallet package to handle topic models trained by mallet and starting to implement some postprocessing an bayesian checking of topic models in R. This is not a part of the standard topicmodels package.

I was thinking of putting it to its own package because the dependencies will need some additional packages only needed if you want to work with the topic models.

**Comment by juliasilge** [comment]
Hello there, Måns! We've been meaning to get back to you on this. It is a plan of Dave and mine to implement a tidying method for topic modeling using [mallet](https://cran.r-project.org/web/packages/mallet/index.html) in the same way that we have a [tidying method for LDA objects from topicmodels](https://github.com/juliasilge/tidytext/blob/master/R/lda_tidiers.R); we would then have a vignette, etc for the mallet topic models. We do not have plans to implement the kind of postprocessing and Bayesian analysis that you are mentioning here, although that sounds great and I would so interested to see your work. Anyway, tidied mallet topic modeling is something to look for coming from us in the (hopefully near) future.

As to your initial question, I would say that the core functionality in tidytext (like `unnest_tokens` and the `tidy`/`cast` framework) is stable, yes.

**Comment by MansMeg** [comment]
Hi! 
Great! I have started to work with a tidytopics package now that is built upon tidytext that can take mallet objects and return them to tidy format (one topic indicator per token and row). And it works really nice for post analysis of topic models using the dplyr framework.

If you would like I can send you a message as soon as the package is in beta (probably next week) and we can discuss if there is some parsing functions that you would like as pull request to get the basic functionality inte tidytext.

**Comment by juliasilge** [comment]
Hello there, Måns! We've got the [tidiers for the mallet package](https://github.com/juliasilge/tidytext/blob/master/R/mallet_tidiers.R) all set up and going so I'm going to close this issue. You can see some worked examples in the [topic modeling](http://tidytextmining.com/topicmodeling.html) chapter of our book.
