### ISSUE TITLE
Sentiment data frame

### ISSUE THREAD

**Issue by dgrtwo** [juliasilge/tidytext#25]
Before the new release, I've been concerned about something. I use code like this a lot in my analyses, often as the only setup needed before a long text-mining pipe:

```
AFINN <- sentiments %>%
  filter(lexicon == "AFINN") %>%
  select(word, score)
```

When we were originally creating the sentiments data frame we wanted to combine them all in one tidy structure, in case someone wanted to do a cross-lexicon analysis. That's still a plausible use case, but overwhelmingly often I choose just one lexicon to use in an analysis. I think we should support that case more easily

I think we should either, in rough descending order of my preference:
1. Have a function `get_sentiments` that supports `get_sentiments("AFINN")`, `get_sentiments("bing")`, etc that pre-perform those 
2. Have functions `get_sentiments_afinn()`, `get_sentiments_bing()`, etc
3. Have them stored as separate datasets (which does have package size implications if we also include the full dataset, and reverse compatibility implications if we don't)

I think it's important to get these out in this week's CRAN release, and not hard to write (I'm happy to do it)

**Comment by juliasilge** [comment]
I like this idea! I think this would be an improvement and really nice for piping.

I am not a big fan of option 3, but options 1 and 2  seem both good to me.

Just to clarify, these would be functions that do specific things for each dataset, like for Bing this?

```
bing <- sentiments %>%
  filter(lexicon == "bing") %>%
  select(-score)
```

If you write up the functions, I will update the README and vignettes. (Unit tests? You/me?)

**Comment by dgrtwo** [comment]
I've got it covered.

One question- should we change AFINN in the main dataset to be lowercase (or nrc to be uppercase)? The inconsistency is a bit bothersome, but the change wouldn't be reverse compatible. (I'd go back and change my Trump and Yelp posts to use afinn rather than AFINN since I want that code to remain functional, and we could do the same throughout the book)

**Comment by juliasilge** [comment]
The original reason we did "AFINN" all caps way back at the unconference was that the [people who put that lexicon together use uppercase for it](http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=6010); it was actually you who wanted to keep it all caps at the time. I'm not sure why we didn't use caps for the [NRC lexicon](http://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm) by similar arguments?!?!?! I guess it's less of a name per se? Anyway, I feel pretty neutrally about this but I do in principle lean toward keeping things lower case and consistent.

If you went with option 2 above, we could keep the new functions all lovely/consistent/lower case AND keep the original data set reverse compatible.

**Comment by dgrtwo** [comment]
OK I went with option 1, but had a special case that turned "afinn" to "AFINN" (so the function takes the argument "afinn" while the data frame hasn't changed).

It's not perfect, but I suspect that once we start shifting examples over to use get_sentiments, basically no one will use the original sentiments dataset.

I've added unit tests and am altering the vignettes/readme now
