### ISSUE TITLE
Implement tidier for topic models from mallet

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/tidytext#26]
Let's write a tidier for the topic models from [mallet](https://cran.r-project.org/package=mallet) along the lines of the [LDA tidier for topicmodels](https://github.com/juliasilge/tidytext/blob/master/R/lda_tidiers.R).

**Comment by cschwem2er** [comment]
Hi there! Thank you for this awesome package :) I would also like to add [structural topic models](https://github.com/bstewart/stm) to the wishlist, which has become an important part of social science research on textual data.

**Comment by juliasilge** [comment]
I looked at this today, and that looks doable (maybe even easier because a) no rJava dependency and b) it has the same input as the topicmodels LDA function). I expect we can add this functionality. 👍

**Comment by dgrtwo** [comment]
I've been experimenting with adding this and I like how it comes out! Will need a few more days to finish it up though

**Comment by cschwem2er** [comment]
Awesome! Is there already a working version?

**Comment by juliasilge** [comment]
Tidiers for mallet topic models are implemented now in commit 8d061931319e932dd8d8c2409b8e3e64303a0097, for those who would like to check it out.

**Comment by cschwem2er** [comment]
Awesome! Thanks :)

**Comment by cschwem2er** [comment]
STM is still in progress?

**Comment by juliasilge** [comment]
Yep, still on the table! I was just playing around with it last night.

**Comment by kevinbsc** [comment]
Any progress on STM? Thanks!

**Comment by juliasilge** [comment]
Need to put something in the topic modeling vignette about mallet.

**Comment by cschwem2er** [comment]
hi, I'm very sorry for annoying you with yet another STM request. But I'd be very interested in this feature for a shiny app. Are there major problems with the STM tidier? Is this something an average R user can help you with?

**Comment by juliasilge** [comment]
@methodds Well I did open an issue for it, at least, in #51. I do not think there are going to be any major problems getting it going; it is just a matter of getting to it! In the meantime, if you want to get an idea for it, you can take a look at [tidiers in broom](https://github.com/tidyverse/broom/tree/master/R) and the [mallet](https://github.com/juliasilge/tidytext/blob/master/R/mallet_tidiers.R) and [topicmodels](https://github.com/juliasilge/tidytext/blob/master/R/lda_tidiers.R) tidiers.
