### ISSUE TITLE
Nicer deprecation?

### ISSUE THREAD

**Issue by Ironholds** [juliasilge/tidytext#32]
The deprecation [here](https://github.com/juliasilge/tidytext/blob/master/R/pair_count.R#L61) isn't really deprecation, since that's [defined as](https://en.wikipedia.org/wiki/Deprecation#Software_deprecation):

>While a deprecated software feature remains in the software, its use may raise warning messages recommending alternative practices; deprecated status may also indicate the feature will be removed in the future. Features are deprecated rather than immediately removed, to provide backward compatibility and give programmers time to bring affected code into compliance with the new standard.

`pairwise_count` just refuses to be used; it's in effect entirely removed. Could I suggest either using `.Deprecated` and allowing it to continue running, going for `.Defunct` instead, or straight-up removing it?

**Comment by dgrtwo** [comment]
We were following [this practice in R Packages](http://r-pkgs.had.co.nz/release.html#undefined) for a bit: I think we had it warn before entirely stopping (I didn't know about the `.Defunct` function, nice). I agree and I've removed it entirely now (it was never a particularly important or used function in tidytext; it will be in widyr)

Thanks!
