### ISSUE TITLE
Provide nest_tokens() as an approximate inverse to unnest_tokens()

### ISSUE THREAD

**Issue by petereckley** [juliasilge/tidytext#35]
Of course this can be achieved with tidyr::nest(). Proposing a wrapper to allow tidytext users to operate within the grammar of the package.

**Comment by ktw5691** [comment]
This would be very helpful. I've been writing workarounds using purrr::by_slice(), but it's messy.

**Comment by juliasilge** [comment]
While we are pondering how and/or whether to implement this within the package, [here is how I typically "undo" `unnest_tokens()`](https://stackoverflow.com/questions/46734501/opposite-of-unnest-tokens/46737676#46737676).

**Comment by juliasilge** [comment]
I am cleaning up some old issues here! 🚀 

Since there are a number of ways to do this in just a few lines of tidyverse code (depending on your use case), we do not plan to add support for this in tidytext in the near future. Thank you for your thoughtful feedback!
