### ISSUE TITLE
unnest_tokens drops attributes of its input data.frame

### ISSUE THREAD

**Issue by petereckley** [juliasilge/tidytext#38]
Is this intended behaviour? I note that tidyr::unnest also destroys attributes, though tidyr::nest preserves them  ([#272 at tidyr](https://github.com/tidyverse/tidyr/issues/272)). Makes it harder to use unnest_tokens with subclasses of data.frame, since you then have to take care to save the old attributes before calling unnest_tokens, and then restore them afterwards.

**Comment by Ironholds** [comment]
@petereckley could you provide an example of this happening? I plan to fix it over the next few days and a reproducible example would be hecka useful for making sure that the fix is actually a fix!

**Comment by juliasilge** [comment]
@Ironholds This is one of the things we need to fix before the next release.
