### ISSUE TITLE
Casting to matrix with term constraints

### ISSUE THREAD

**Issue by 1danjordan** [juliasilge/tidytext#39]
First of all I want to thank you and David Robinson. tidytext and Text Mining in R are absolutely brilliant! I have a feature suggestion, which may or may not be within the scope of the package.

I've been working with the apartment rental listing data from [this](https://www.kaggle.com/c/two-sigma-connect-rental-listing-inquiries) Kaggle competition. It contains text tags for each apartment listing. I've been using tidytext to analyse, transform and cast to DTMs. 

My goal is to predict the interest level of a listing given its feature tags. The `cast_` functions have been tremendous for creating a set of training data for training a model, but I have a challenge. The training data produces an n x m DTM - so there are m terms in the set. I train a model with this matrix, but the test data won't necessarily have the same m terms. I could include both in the dataset for casting and then separate them, but then I have to recast every time I have a new listing to predict. 

It would be great to constrain the set of m terms that get cast to the DTM (kind of like the opposite of stop words). Then I could do something like:

```r
allowed_terms <- c("bright", "hardwood", "cosy")

dtm <- get_some_text() %>%
  unnest_tokens(term, text) %>%
  count(document, term) %>%
  cast_sparse(document, term, n, allowed_terms = allowed_terms)
```

This would mean any new observation with a set of features could be standardised as input into the model (for example if a new observation contained none of the allowed terms, then it would be cast to a 1 x m matrix of zeroes). 

I would be happy to work on this feature and make a pull request if you thought it was a reasonable feature to be included. Thanks again, your work is amazing!

Cheers,
DJ

**Comment by dgrtwo** [comment]
Thanks for your feedback! In most cases, this is best handled by dplyr steps rather than an extra argument in `cast_` functions:

* a `mutate` to turn document into a factor
* a `filter` to remove words not in the allowed terms `filter(term %in% allowed_terms)`. If all you want is to have a "whitelist" of terms, this does it.
* a `mutate` that turns the words into a factor with the levels you want `factor(term, levels = allowed_terms)`. This allows you to keep the order consistent and include terms not present in the data.

Here's an example:

```r
dataset <- data_frame(document = 1:3,
                      text = c("nice apartment", "cosy home", "very cosy home"))

dataset %>%
  unnest_tokens(term, text) %>%
  mutate(document = factor(document)) %>%
  filter(term %in% allowed_terms) %>%
  mutate(term = factor(term, levels = allowed_terms)) %>%
  count(document, term) %>%
  cast_sparse(document, term, n)
```

Result:

```
3 x 3 sparse Matrix of class "dgCMatrix"
  bright hardwood cosy
1      .        .    .
2      .        .    1
3      .        .    1
```

The one case I'd be concerned about is when the allowed terms never appear in the documents at all. Is this a common use case for you?

**Comment by 1danjordan** [comment]
Hey David, thanks for getting back so quick. I thought something in dplyr would work, but wasn't able to figure it out myself!

I suppose in the case where allowed terms never appear in the document at all, then that document will be filtered out all together, which was really what I was most concerned with. Ideally, given a model is trained with a constrained DTM, any new observations could be reliably cast into the same DTM for prediction. This is not a common use case for me (I'm totally new to text mining), but was something I ran into quickly and imagined might be common/useful. I came across the `dictionary` function from quanteda which does something similar, although it also groups words together too.

**Comment by dgrtwo** [comment]
> I suppose in the case where allowed terms never appear in the document at all, then that document will be filtered out all together, which was really what I was most concerned with.

Luckily, that doesn't happen because of the `mutate(document = factor(document))` line: notice that my document 1 ("nice apartment") is retained as an empty row in the output.

The only case that truly breaks is if there are no allowed words pairs in the entire dataset.

**Comment by 1danjordan** [comment]
Ah, I didn't realise! Brilliant, thanks a million :1st_place_medal:
