### ISSUE TITLE
dependency in Travis for XML package

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/tidytext#4]
OK, the XML package is a "suggests" dependency of quanteda and it is not getting built on Travis currently for the tidying_casting.Rmd vignette
[https://travis-ci.org/juliasilge/tidytext/builds/124871786](https://travis-ci.org/juliasilge/tidytext/builds/124871786)

[Here](https://cran.r-project.org/web/packages/XML/index.html) is XML on CRAN.

I think [this](https://github.com/craigcitro/r-travis/issues/66) has the answer of what we need to change, but I haven't tried yet.

**Comment by juliasilge** [comment]
Maybe this is what we want:
http://stackoverflow.com/questions/7765429/unable-to-install-r-package-in-ubuntu-11-04/7769023#7769023

**Comment by juliasilge** [comment]
Well, using this:
`sudo apt-get install r-cran-xml`
did not work:
https://travis-ci.org/juliasilge/tidytext/builds/124875997

**Comment by juliasilge** [comment]
How does quanteda get around this? By not building the vignettes on Travis:
https://github.com/kbenoit/quanteda/blob/master/.travis.yml

Do we want to do this? It means we could also take out the bit to install topicmodels, right?

**Comment by juliasilge** [comment]
I tried using this:
`- ./travis-tool.sh aptget_install r-cran-xml`
as found [here](https://github.com/csgillespie/travis-examples/tree/master/xml), but that also did not work:
https://travis-ci.org/juliasilge/tidytext/builds/124902849

The example I tried here is almost 2 years old so I am not shocked that it did not work.

**Comment by juliasilge** [comment]
I just noticed that this build on Travis failed during checking an example, not during building the vignette. This is... different? If you look at the [build history](https://travis-ci.org/juliasilge/tidytext/builds), the ones that failed couldn't find XML when checking an example and the ones that errored couldn't find XML when building a vignette.

**Comment by juliasilge** [comment]
OK, @dgrtwo, it is definitely the example for tidy.Corpus. The vignettes build fine with the current version of .travis.yml so I think we had more than one problem before: both a problem with the .travis.yml and a problem in the example for tidy.Corpus. I may be wrong, but I believe that .travis.yml is working now and we just need to fix something (?) in the example for tidy.Corpus. 

And I am OUT for the day. 😉 Don't forget to git pull before working; we had some messed up stuff in one of the vignettes because of merging.

**Comment by dgrtwo** [comment]
Great work! Eesh this is tough. But yeah I'll fix the tidy.Corpus examples tomorrow. (Also have some unit tests to write).

I'd really like to submit 0.1.0 to CRAN by Sunday since I'm planning to include it in a class on Monday morning. I feel like we're very close to that point!

**Comment by juliasilge** [comment]
Fixed with commit aaacd21834cd6aaf74e0b33f4e5d990adca1949e
