### ISSUE TITLE
Difference in n-grams between tidytext and tm?

### ISSUE THREAD

**Issue by andypicke** [juliasilge/tidytext#40]
Hi, I was using tidytext for a project where I was trying to make a text prediction algorithm. This involves tokenizing text into n-grams, and I noticed a difference between the results using tidytext vs using the tm package. Basically it seems that if you have multiple lines of text, tm computes n-grams for each line separately, whereas tidytext computes n-grams for all the lines pasted together (so you get n-grams that span lines). I'm not sure if there is a 'correct' method . If your text is liked the tidytext examples from gutenbergr, it makes sense because each line of text appears in order in the book. But in my case, each line was a different article or tweet for example, so an n-gram spanning lines wouldn't make sense (because those words never actually occur together in that order). But I thought it might be worth pointing out in a vignette or something since people might assume you get the same results as with tm. I made a little example of this in the attached file.

[tidytextVStm.pdf](https://github.com/juliasilge/tidytext/files/788652/tidytextVStm.pdf)

**Comment by dgrtwo** [comment]
You're right about the difference and this is a good observation. The way to fix it is to set `collapse=FALSE` in the arguments to `unnest_tokens`, e.g.:

    bi <- unnest_tokens(df, ngram,corpus,token="ngrams",n=2,collapse=FALSE)

We note this in the docs for `unnest_tokens`, in the `collapse` argument and in details:

> If the unit for tokenizing is ngrams, skip_ngrams, sentences, lines, paragraphs, or regex, the entire input will be collapsed together before tokenizing.

It may be worth expanding on those docs if it wasn't clear.
