### ISSUE TITLE
could not find function "get_sentiments"

### ISSUE THREAD

**Issue by kjmobile** [juliasilge/tidytext#41]
require(tidytext)
ap_td<-tidy(AssociatedPress)
ap_td
ap_sentiments<-ap_td %>%inner_join(get_sentiments("afinn"), by=c(term="word"))

I see this: 

Error in is.data.frame(y) : could not find function "get_sentiments"

**Comment by juliasilge** [comment]
Hmmmmm, have you tried to `update.packages()` lately?

**Comment by kjmobile** [comment]
Packages are all updated.  But.. I am using old version of R (R 3.1.3). Would that be a problem?

**Comment by kjmobile** [comment]
Julia,
get_sentiments() works after I upgraded R from 3.1.3 to 3.3.2.
After upgrade, I could update more packages. Especially one named "Lazyeval".
Thank you for your great book!

**Comment by juliasilge** [comment]
That would do it, I expect! Good luck. 🙌
