### ISSUE TITLE
unnest_tokens when token = "characters" removes spaces

### ISSUE THREAD

**Issue by yeedle** [juliasilge/tidytext#45]
This is definitely not a bug, but I've run into a situation where I split up a document into characters using `unnest_tokens`, but now I need to know whether any given character is at the beginning of a word or not. The easiest way to find out would be if I were able to ask the tokenizer to preserve spaces between characters and then I could check if `lag(token)` is a space. Is that a possibility?

**Comment by yeedle** [comment]
This is embarrassing. Just reread the docs, and realized that I could just pass along `strip_non_alphanum = F` to the tokenizer. D'oh!

**Comment by dgrtwo** [comment]
This is still good to learn, I didn't know about it!
