### ISSUE TITLE
Text Tidying tools for R?

### ISSUE THREAD

**Issue by pgensler** [juliasilge/tidytext#48]
Have you thought about putting together a list of commonly done operations to clean text for analysis within tidytext? I know this is much more of a data cleansing task, but I think having some resources laid out such as packages like qdap, textclean, stringi/stringr can be helpful when prepping text for analysis purposes. The data below is  wine reviews from here: http://snap.stanford.edu/data/cellartracker.txt.gz, which has almost 2 million wine reviews. It is relatively large, but might even be worth using as an example within you book. Consider this example of wine reviews from a raw txt file, and removing html tags, html unicode, and key value pairs of data:

> wine/name: 2001 Le Clos du Caillou C&#244;tes du Rh&#244;ne Villages Tres Vieilles Vignes Reserve
> wine/wineId: 3688
> wine/variant: Red Rhone Blend
> wine/year: 2001
> review/points: 93
> review/time: 1096243200
> review/userId: 1
> review/userName: Eric
> review/text: This wine continues to wow me. The nose is sweet and herbal with garrigue pouring from the glass along with a laser-focused core of brambly raspberry and some duskier scents of licorice and, from the right glass, some roasted meat. On the palate this is impeccably balanced, pure and powerful. The wine seems to have closed up a tiny bit from prior tastings, yet it juggles well between a core of sweet fruit and some nice elements of minerality. There is a lush, silky, enveloping texture that just washes over the palate in a very inviting way. The wine finishes powerfully with some hints of sour cherry and lovely, dusty, tooth-coating tannins. Delicious!<br /><br />I also decided to try an experiment to see which Riedel glass format would work best for the wine. I took out four glasses and filled each glass roughly 1/6th of the way up. (My wife wondered who else was coming over for dinner...) Generally speaking, the most significant difference was on the nose, but I was surprised at how much some of the differences actually carried onto the palate. It seems like that initial sip is heavily flavored by what you smell as you tip the glass, far more than I ever imagined:<br /><ul type='square'><li><b>Riedel Vinum Chianti/Zin:</b> Excellent all-purpose glass. The nose was nicely balanced with the raspberry really coming out and nice waves of garrigue.<br /><li><b>Riedel Vinum Syrah:</b> Hands down the best glass. It was like a bigger, more intense, more focused version of the Chianti glass. The garrigue really comes forward, but the big, tall bowl and narrow nose seems to amplify the bouquet quite a bit. Also, complex elements of smoke and roasted meat come to life. Wow, this is almost like a different wine.<br /><li><b>Riedel Vinum Bordeaux:</b> This one was puzzling. For some reason the nose on this glass was the least focused and most diffuse. I could smell all the same elements as in the prior two glasses, but the wine literally seemed to wander. It didn't know what it wanted to be. I had to work to smell the same things, and even then it was like I had to convince myself of what I was smelling. The one word summary is diffuse.<br /><li><b>Riedel Vinum Burgundy:</b> This is the one glass that brings forward a sharp, almost painful note of alcohol. I really did not enjoy the wine from this glass.</ul><br />I actually found this experiment a bit disturbing. I like my Riedel's a lot, but I never really expected the marketing hype to be as true to reality as I saw tonight. I have a bad feeling that in the future I will have more glassware to wash, as frankly I will likely try the same wine from a few glasses. It is highly educational!<br /><br /><b>DAY 2:</b> Still going strong. Smooth as velvet, rich, deep and integrated. Excellent!

As much as I would love to start utilizing your package to analyze reviews like these, there is definitely more than one way to parse out the html tags, and convert unicode characters to make this file readable. However, it has been quite a challenge to find resources on tidying data like this for analysis work with tidytext.
Maybe adding a chapter to the tidytext mining book regarding text cleaning would be the best approach? Even character representation such as #244; can mess up the encoding of the file you want to read in, which gives file encoding errors in r.It might be worthwhile to have a brief section regarding file encoding, and how that impacts text data for analysis. Not to sound harsh, but this is simply my feedback. I look forward to working with your package for my analysis!

**Comment by juliasilge** [comment]
Hello there, Peter! Cleaning text is definitely a challenge. In the book, we went the direction of including information on cleaning text within the case studies, not in a separate chapters. There are notes on how we cleaned text in the chapter on [NASA metadata](http://tidytextmining.com/nasa.html) (which included HTML tags), the [Usenet chapter](http://tidytextmining.com/usenet.html) (where we cleaned headers and such), and the [Twitter chapter](http://tidytextmining.com/twitter.html) (where we talked about using regex to extract words and Twitter hashtags/usernames/etc).

There are certainly a lot of strategies to use! They are so specific to each dataset that we chose to show how various strategies can be applied in context. These are mostly of the stringr/regex variety. Thanks for sharing your input.

**Comment by pgensler** [comment]
Julia, 

Thanks for your comments. Is there any way to contribute an example to the book? I'm not sure if you have published the book or plan on it. The only reason I ask is that I've encountered so many issues with this single project that it may be worthwhile to include as a case study or vignette if you are willing, as I think it would help others with text mining. Let me know your thoughts on this.

**Comment by pgensler** [comment]
Hi Julia,

Not to beat this issue, but would you be willing to accept PR's for additional vignette's for your package? As I'm going through the NASA chapter in your book, I think that this information is definitely quite valuable, but I'm wondering if it may be helpful to have a one-page summary of resources to turn to for basic text tasks, similar to what you have outlined in your book?
Possibly:
- Dealing with encoding in R, as this can definitely be a pain point (esp. UTF-8 strings)
- JSON parsing, clearly lots of resources
- Web scraping, as more than likely you will need to do it to acquire text from web pages

It's not meant to be a comprehensive tutorial, but I'm curious to see if you think this fits with the spirit of tidy-text. It may very well not be meant for your package, which is fine with me. Let me know, and I'd be willing to help put together a minimal vignette.

This also relates to the janeaustenr package used in tidytext:
https://cran.r-project.org/web/packages/utf8/vignettes/utf8.html

**Comment by juliasilge** [comment]
Peter, thanks so much for your thoughtful comment, and I apologize for being slow to get back to you on this. I think this set of skills is SO IMPORTANT and I see a lot of value in compiling a good list of resources for text cleaning tasks. I literally was just responding to GitHub issues and blog comments from people with encoding issues for non-English languages. 😂 And knowing what to do with JSON or how to scrape the web is also super important.

Vignettes are typically about the code in a package, though, and how to use those functions. I've never seen a vignette that consists mainly of a list of resources external to that package; it is just not the right venue. If you put together this kind of guide and publish it, I would love to link to it from my blog, tweet about it, etc, but I don't think it's right for a vignette. Please let me know if you put together a valuable resource like this and publish it!

**Comment by pgensler** [comment]
Thanks so much for your reply! That's totally understandable, I wish I had used twitter more and more to get help on these issues. Yeah I'm a bit torn as to where to house these resources as I seem to run into these issues more and more, especially with R.

I can understand why it would not make sense to have it located in a vignette. My only gripe is that if I'm a new R user, I want someone to get off on the right foot, and not merely drown in not knowing what to do (like with docker, shameless plug for my blog post: https://medium.com/@peterjgensler/creating-sandbox-environments-for-r-with-docker-def54e3491a3) (to be fair, I saw your dockerfile, and I restrained myself :sob:)

Do you think it's appropriate to have a portion of the readme at the bottom dedicated to simply referring people to resources that may assist them in the data munging process? I know it's not entirely in-line with the package's intent, but it's there if someone needs it?

I'm currently in the process of a creating a blog post using this data as an example, but I feel like I've ran into so many issues that I'm not even sure how to "set someone up for success", given all the troubles I've ran into just trying to get it in a workable format. I wonder if most people (like myself :smiley:) enter into text mining assuming that you can just slam a large ish file (like[ the yelp dataset challenge](https://www.yelp.com/dataset/challenge)) into this, and it should work just fine (which is definitely not the case :joy:). Maybe this is just me, but I've just had a mirage of nightmares attempting to clean this data:
https://community.rstudio.com/t/split-uneven-length-vectors-to-columns-with-tidyr/2704/10
https://stackoverflow.com/questions/43218761/by-row-vs-rowwise-iteration/43236272?noredirect=1#comment75570823_43236272

To give you a bit of context, just merely tokenizing the raw data took over an hour with a different program (called Alteryx), and went from a 1GB file to 17GB (for [one file](https://data.world/petergensler/beer-advocate-reviews), the other is [here](https://data.world/petergensler/ratebeer-reviews))

**Comment by juliasilge** [comment]
A link in the README is a good idea; if you put together a list of resources, let me know and I can add it.

(And I will have to check out your Docker post; I am excited to learn more about good practices for Docker.)

**Comment by pgensler** [comment]
Sounds good, I'll do a roundup, and see what I can come up with. As a new developer, Docker is so worthwhile but the pain......

**Comment by pgensler** [comment]
FYI @juliasilge I intended to write about functions, but a good portion covered encoding issues in R:
https://medium.com/@peterjgensler/functions-with-r-and-rvest-a-laymens-guide-acda42325a77
