### ISSUE TITLE
missing LOUGHRAN lexicon?

### ISSUE THREAD

**Issue by randomgambit** [juliasilge/tidytext#49]
Hello,

First of all, many thanks for this wonderful package that really helps processing text data better and more efficiently!

It seems I am unable to load the `loughran` lexicon. Packages are up to date.
What is the problem here?

```

library(tidytext)
library(tidyverse)


test = data_frame('text' = c('this is a nice test yay'))


# WORKS
test %>% unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word") %>%
  inner_join(get_sentiments('bing'), by = "word") 

# A tibble: 2 × 2
   word sentiment
  <chr>     <chr>
1  nice  positive
2   yay  positive

# FAILS
test %>% unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word") %>%
  inner_join(get_sentiments('loughran'), by = "word") 

Error in match.arg(lexicon) : 
  'arg' should be one of “afinn”, “bing”, “nrc”
```

**Comment by juliasilge** [comment]
This sentiment lexicon is in the development version here on GitHub but not yet on CRAN. Be sure to install from GitHub:

```
devtools::install_github("juliasilge/tidytext")
```

**Comment by randomgambit** [comment]
argh!! I cannot use the development version because I cannot install devtools (I am on a firewalled machine)... any workaround here? thanks @juliasilge !

**Comment by juliasilge** [comment]
Oh bummer... We are preparing a new version for CRAN in the near future but probably not for another several weeks (before our book gets published).

**Comment by juliasilge** [comment]
You could clone the whole repo, put it on your local machine, and use `devtools::install_local()`?

**Comment by randomgambit** [comment]
you mean cloning the whole `tidytext` package?

**Comment by randomgambit** [comment]
anyway... it seems I also need to install `rtools` to make `devtool` work. Not possible as I don't have admin rights. I can only wait until you push the new version on cran! sob sob

thanks @juliasilge :)

**Comment by dgrtwo** [comment]
I've got a short term workaround! You could read the sentiments table from GitHub:

```r
sentiments <- readr::read_csv("https://raw.githubusercontent.com/juliasilge/tidytext/master/data-raw/sentiments.csv")
```

(Or download that file and read it locally). At that point you could use `sentiments %>% filter(lexicon == "mcdonald")` in place of using `get_sentiments()`.

**Comment by randomgambit** [comment]
@dgrtwo awfully wonderful! (sentiment = ?) 

thanks!

**Comment by znmeb** [comment]
IIRC you can download  the tarball and install from the command line with R CMD install, but I haven't tried it recently.

**Comment by randomgambit** [comment]
actually the solution by @dgrtwo works perfectly fine. A quick follow up. Which version of the dictionary are you using? I see on https://www3.nd.edu/~mcdonald/Word_Lists.html that there has been an update in 2015. In any case, keep up the good work, this package is G R E A T
