### ISSUE TITLE
Implement tidiers for topic models from stm package

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/tidytext#51]
Let's write tidiers for the topic models from [stm](https://github.com/bstewart/stm). This package has no rJava dependency and the same input as the topicmodels LDA modeling.

**Comment by cschwem2er** [comment]
Hi, 
is this currently in development? I'd love to combine tidytext and stm for teaching in mid October and a tidier function would be most useful for this.

**Comment by juliasilge** [comment]
I worked on this some today and it is almost good to go! Should be ready very shortly, in time for your course.

**Comment by cschwem2er** [comment]
that's awesome, thank you so much for this :)

**Comment by juliasilge** [comment]
@methodds Got this finished up this evening. Give it a go and please let us know if you run into any problems!

**Comment by cschwem2er** [comment]
Hi,
I just tested the latest version and it works without any issues, again thank you so much for implementing this! :)

There's only one suggestion that I have for your example in ````stm_tidiers````:  STM offers the spectral method for model initialization which, unlike the usual initialization for LDA models, is deterministic (more details on that in the [STM vignette](https://cran.r-project.org/web/packages/stm/vignettes/stmVignette.pdf)). The spectral method is highly recommended by the STM authors.
For this reason I think you should remove the seed, ``set.seed(2016)`` and just slightly adjust the ``stm`` call to ``topic_model <- stm(inaug, K = 3, verbose = FALSE,
                   init.type = 'Spectral')``.

**Comment by cschwem2er** [comment]
Sorry just another quick question related to this: Do you have a time schedule for the next CRAN release? I dunno about other countries, but university courses in Germany start mid/end October and getting devtools to run in our labs is a real pain.

**Comment by juliasilge** [comment]
@methodds I will see what we can do about a quick-ish CRAN release! I'd like to get the tidyeval stuff all worked out for all the functions.

**Comment by juliasilge** [comment]
@methodds Just a heads up that the version of tidytext with stm tidiers is on CRAN now.
