### ISSUE TITLE
Internationalise stop_words

### ISSUE THREAD

**Issue by Ironholds** [juliasilge/tidytext#53]
From #22 : 

Include multilanguage options for stopwords. This is a useful thing with or without other internationalisation changes. So this would consist of:

1. Expanding the stopword sets stored in the package
2. Adding a parameter to `stop_langs` to select languages
3. Adding a new function, `stop_languages()` that returns a set of which languages are supported by `stop_words`.

I will probably work on this over the next few days.

**Comment by Ironholds** [comment]
Argh. So it looks like the other language variants of the initial dictionary are (1) not freely accessible and (2) just google translate :|. Any objections to using different corpora for the non-en stopwords?

**Comment by juliasilge** [comment]
We are putting internationalization work on hold until *after* our next CRAN release (0.1.3) and will start it heading toward 0.1.4.

**Comment by Ironholds** [comment]
Makes sense.

**Comment by cschwem2er** [comment]
Hi,
why don't you make use of @kbenoit 's quanteda multi language capabilities? They have, for instance, several language specific [stop word lists](https://rdrr.io/cran/quanteda/man/stopwords.html).

**Comment by juliasilge** [comment]
@methodds Thanks again for the suggestion. This was implemented in commit 991c4df122bb9af26ef7a785541e42d484d48f5a.

**Comment by kbenoit** [comment]
Note that the upcoming CRAN refresh of **quanteda** will move to reliance on the [**stopwords** package](https://github.com/davnn/stopwords), implemented in https://github.com/kbenoit/quanteda/pull/1159. 

This has international stopwords but also bases its core on a principled set, the Snowball list.  (It also includes the more inclusive “stopwords-iso” list for about 57 languages, which has wider coverage but is not very systematically collected.)

**Comment by juliasilge** [comment]
Wow, thanks, @kbenoit.
