### ISSUE TITLE
Qualifiers dataset(s)

### ISSUE THREAD

**Issue by stephlocke** [juliasilge/tidytext#55]
Would the addition of datasets of sentiment qualifiers like negations and adverbs be of interest to add in?
e.g. 

```
negations
-------
cannot
could not
did not
does not
had no
have no
may not
never
no
not
nothing
was no
was not
will not
would not
ain't
aint
can't
cant
couldn't
didn't
doesn't
don't
dont
hasn't
haven't
won't
```

Compiled from datasets available from [Sentiment Composition Lexicons](http://www.saifmohammad.com/WebPages/SCL.html)

**Comment by Ironholds** [comment]
Would #47 cover this?

**Comment by stephlocke** [comment]
Not for being able to easily negate sentiment based on bigrams with negations in - though it's great to expand the lexicons and I'd really love to see the international lexicons in there!

**Comment by juliasilge** [comment]
This is a really great idea, @stephlocke, and would be a great addition to the datasets in this package, similar to [`stop_words`](https://github.com/juliasilge/tidytext/blob/master/R/stop_words.R). Are you interested in working on it and contributing? If so, I think the data set should be called probably `negate_words`, and it should be one word per row. This means excluding things on this list like "may not" but instead just using "not". Contractions are good to be included. 👍 

If you want to work on this, please follow the format of the documentation for the `stop_words` data set and include the link(s) to the source(s).

**Comment by stephlocke** [comment]
Will do! (sorry for the delay in response)
