### ISSUE TITLE
get_sentiments("loughran")

### ISSUE THREAD

**Issue by fibrou** [juliasilge/tidytext#56]
I am working through your "Text Mining with R" and I am getting a 'bug' with the Loughran and McDonald sentiment lexicon in the "get_sentiments" function.  Seems like the "loughran" lexicon is not recognized as an option in the get_sentiments function.  I see you appear to be working on the matter, but I can't determine if you have 'solved' the issue.  How can I incorporate the Loughran and McDonald lexicon in the get_sentiments function?

Thank you for writing such a cool tool and book!  Just excellent!

**Comment by dgrtwo** [comment]
That version isn't yet on CRAN (expect it soon!), but for now you can fix it by installing the development version on GitHub:

    devtools::install_github("juliasilge/tidytext")

Thanks for your comments!

**Comment by fibrou** [comment]
Thanks!  I was going to create my "own" LM_sentiment tidy tbl, but now don't need to. You have done it for me.

BTW, I am a finance professor teaching myself textual and sentiment analysis. Your tidy approach makes things SO MUCH EASIER (does that sound like a teenage?) I will be incorporating many of the tools highlighted in your effort in a new 'Financial Data Analytics' course I am creating at Rutgers.

On the other hand, maybe I will create my "own" LM sentiment tidy tbl.  As a check to see if I've learned anything.  :-)

Thanks again for such a great effort!

Thanks again.
