### ISSUE TITLE
Broken unit test

### ISSUE THREAD

**Issue by Ironholds** [juliasilge/tidytext#58]
So the dictionary tidier is now broken. I'm not sure where the change happened (it's either in `quantedata` or `broom` - I suspect quantedata) but input values must be named. This means that, starting from the unit test's position of 'a list of named elements':

1. If you throw in an (unnamed) list, it breaks
2. If you throw in a (named) list, it works but then flubs up with the test expectations, because the output looks different
3. If you throw in two named vectors, it works and `tidy` then rejects it.

@dgrtwo any idea? I've got this patch I'm reworking for Andy and this is messing with it some :/.

**Comment by juliasilge** [comment]
Oh dear...

``` r
lst <- list(terror = c("terrorism", "terrorists", "threat"),
            economy = c("jobs", "business", "grow", "work"))

d <- quanteda::dictionary(lst)

names(d)
#> [1] "terror"  "economy"

library(tidytext)

names(d)
#> NULL
```

:scream::scream::scream:

**Comment by Ironholds** [comment]
Yeah I don't...is it a class masking thing, or?
