### ISSUE TITLE
Column Selector doesn't work

### ISSUE THREAD

**Issue by fahadshery** [juliasilge/tidytext#61]
I have 4 columns in a tibble.
1st is the Date, then the other 3 are `<chr>` type.
When I try to create ngrams by specifying the actual column of "Text" that I am interested in, it always selects a different <chr> column. I have tried rearranging the column positions but it still doesn't work. 
I ended up having to select only the Date and the Text column in order to create ngrams.
Here is the final code:
`consumer_ngrams <- consumer_small %>%
                      select(Date, Text)%>%
                      mutate(feedback_no = row_number())%>%
                      unnest_tokens(ngram, Text, token = "ngrams", n = 2)`

**Comment by juliasilge** [comment]
That sounds pretty strange, and I can't say I've run into that. Can you make a reproducible example with some bit of example data that produces this behavior?

**Comment by fahadshery** [comment]
Here is the `dput` for an extract

`structure(list(Date` = structure(c(16436, 16436, 16436, 16436, 
16436), class = "Date"), `GSAT1S_01New Thinking about the brands you are currently with  overall how satisfied are you with... SKY` = c("Fairly Satisfied", 
"Fairly Satisfied", "Extremely Dissatisfied", "Fairly Satisfied", 
NA), NPS_Level = c("Passive", "Passive", "Detractor", "Passive", 
"Passive"), `Converted NPS` = c(NA_character_, NA_character_, 
NA_character_, NA_character_, NA_character_), Text = c("ant that good", 
"Because broadband speed is so low I have to pay for SKY Business to get a decent speed and no slowing during peak time. Also there is no sign of fibre optics coming here soon", 
"because i am a customer and there products especially broadband are rubbish and dont work and they have done nothing about it", 
"Because the internet conection does not support more than one device at a time despite advertising otherwise", 
"Because the prices are extortionate")), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -5L), .Names = c("Date", 
"GSAT1S_01New Thinking about the brands you are currently with  overall how satisfied are you with... SKY", 
"NPS_Level", "Converted NPS", "Text"))`

**Comment by juliasilge** [comment]
Looks like the problem is your column names; they are not well-formed, contain some wacky characters and spaces, etc. I could not get that `dput` to read in to R at all. However, if I changed the names of your columns, things worked out fine:

``` r
consumer_ngrams <- structure(list(Date = structure(c(16436, 16436, 16436, 16436, 16436), class = "Date"), 
                          NPS = c("Fairly Satisfied","Fairly Satisfied", "Extremely Dissatisfied", "Fairly Satisfied", NA), 
                          NPS_Level = c("Passive", "Passive", "Detractor", "Passive","Passive"), 
                          Converted_NPS = c(NA_character_, NA_character_, NA_character_, NA_character_, NA_character_), 
                          Text = c("ant that good","Because broadband speed is so low I have to pay for SKY Business to get a decent speed and no slowing during peak time. Also there is no sign of fibre optics coming here soon",
                                   "because i am a customer and there products especially broadband are rubbish and dont work and they have done nothing about it",
                                   "Because the internet conection does not support more than one device at a time despite advertising otherwise",
                                   "Because the prices are extortionate")), class = c("tbl_df","tbl", "data.frame"), 
                     row.names = c(NA, -5L), 
                     .Names = c("Date", "Satisfaction",
                                "NPS_Level", "Converted_NPS", "Text"))

consumer_ngrams
#>         Date           Satisfaction NPS_Level Converted_NPS
#> 1 2015-01-01       Fairly Satisfied   Passive          <NA>
#> 2 2015-01-01       Fairly Satisfied   Passive          <NA>
#> 3 2015-01-01 Extremely Dissatisfied Detractor          <NA>
#> 4 2015-01-01       Fairly Satisfied   Passive          <NA>
#> 5 2015-01-01                   <NA>   Passive          <NA>
#>                                                                                                                                                                             Text
#> 1                                                                                                                                                                  ant that good
#> 2 Because broadband speed is so low I have to pay for SKY Business to get a decent speed and no slowing during peak time. Also there is no sign of fibre optics coming here soon
#> 3                                                  because i am a customer and there products especially broadband are rubbish and dont work and they have done nothing about it
#> 4                                                                   Because the internet conection does not support more than one device at a time despite advertising otherwise
#> 5                                                                                                                                            Because the prices are extortionate

library(dplyr)
library(tidytext)

consumer_ngrams %>% 
    mutate(feedback_no = row_number()) %>% 
    unnest_tokens(ngram, Text, token = "ngrams", n = 2) %>%
    select(-Date, -Converted_NPS)

#> # A tibble: 77 x 4
#>              Satisfaction NPS_Level feedback_no                ngram
#>                     <chr>     <chr>       <int>                <chr>
#>  1 Extremely Dissatisfied Detractor           3            because i
#>  2 Extremely Dissatisfied Detractor           3                 i am
#>  3 Extremely Dissatisfied Detractor           3                 am a
#>  4 Extremely Dissatisfied Detractor           3           a customer
#>  5 Extremely Dissatisfied Detractor           3         customer and
#>  6 Extremely Dissatisfied Detractor           3            and there
#>  7 Extremely Dissatisfied Detractor           3       there products
#>  8 Extremely Dissatisfied Detractor           3  products especially
#>  9 Extremely Dissatisfied Detractor           3 especially broadband
#> 10 Extremely Dissatisfied Detractor           3        broadband are
#> # ... with 67 more rows
```

Try using only letters, numbers, and punctuation like underscores in your column names, and I bet you will have no problems!

**Comment by fahadshery** [comment]
Perfect! That's what i thought... thank you. closing the issue now
