### ISSUE TITLE
might be useful

### ISSUE THREAD

**Issue by hrbrmstr** [juliasilge/tidytext#68]
<https://github.com/hrbrmstr/hgr/blob/master/inst/xslt/justthetext.xslt> is an XML style sheet that I've put into a ridiculously simple function <https://github.com/hrbrmstr/hgr/blob/master/R/clean.r> in my Mercury Postlight API pkg.

It strips all HTML tags out of a document, leaving just the text. Only mentioning it as it might be something to consider adding (likely after improving) to `tidytext` if an `xslt` dependency is tolerable.

**Comment by dgrtwo** [comment]
Oh, this looks great! I run into this often, and the [hunspell html parser](https://github.com/juliasilge/tidytext/commit/c78fbc54a2f25d8fb52ec9e6c9660115c7f6a09d) can be very slow.

I seem to recall xml2 (which xslt needs) being a bit of a tough dependency, especially on Travis, so we'll have to dive into this a little bit first.

**Comment by juliasilge** [comment]
I'm cleaning up old issues! 🚀 

The dependency here is tough and we haven't heard a high demand for this recently, so I'm going to close this. Thank you for your feedback! 🙌
