### ISSUE TITLE
import data from excel

### ISSUE THREAD

**Issue by TheOne000** [juliasilge/tidytext#72]
Dear Contributors
     I have text data in Excel. One row is one document. SO, How can I import that file into tidy text to create the term matrix document and to implement LDA?
Thank you

**Comment by juliasilge** [comment]
For reading data from Excel into R, I really like the [readxl](https://github.com/tidyverse/readxl) package.

Once your data is in R, you can first tidy it and explore it, looking at the most common terms, making some exploratory plots, and such. Then you can convert it to a document-term matrix for topic modeling. Check out the chapters on [topic modeling](http://tidytextmining.com/topicmodeling.html) and the case study on [NASA data](http://tidytextmining.com/nasa.html) from our book to see code examples for how to do this.
