### ISSUE TITLE
Please upgrade tidytext to tidyeval so dplyr 0.7.* rlang parametrics will work

### ISSUE THREAD

**Issue by dan-reznik** [juliasilge/tidytext#74]
### loads required libraries
```{r}
library(tidyverse)
library(tidytext)
```
### creates to 2-row tibble, test simple operation (it works)
```{r}
df <- tribble(~id,~descr,1,"hello bug",2,"goodbye bug")
df %>% select(id,descr) %>% unnest_tokens(word,descr)
```
> A tibble: 4 x 2
>     id    word
>  <dbl>   <chr>
>1     1   hello
>2     1     bug
>3     2 goodbye
>4     2     bug

### creates a parametrized dplyr 0.7.* version of the above
```{r}
myFn <- function(df, col1,col2) {
  col1 <- enquo(col1)
  col2 <- enquo(col2)
  df %>%  select(!!col1, !!col2) %>% # works
    unnest_tokens(word, !!col2) # this won't work
}
```

### Call to myFn below pukes at unnest_tokens()
```{r}
myFn(df,id,descr)
```
>Error: Invalid column specification

**Comment by juliasilge** [comment]
Related to #67

**Comment by dan-reznik** [comment]
Julia I don't think it's related to that other Issue which is about non-standard column names. In my case it's related to non-compatibility with the latest dplyr 0.7.* capabilities for creating parametric functions.

I had originally posted this Issue on the dplyr github page but the author told me the issue was that tidytext is still not a tidyeval library.

Does that make sense?

**Comment by juliasilge** [comment]
Yep, makes sense! I'm pretty sure both issues will be solved by adding tidyeval to our package.

**Comment by dan-reznik** [comment]
That's great! Any chance this could be done soonish...

**Comment by juliasilge** [comment]
Probably not this weekend but it is a priority.

**Comment by juliasilge** [comment]
We now have support for rlang/tidyeval in tidytext!

``` r
library(tidyverse)
library(tidytext)

df <- tribble(~id,~descr,1,"hello bug",2,"goodbye bug")

myFn <- function(df, col1,col2) {
  col1 <- enquo(col1)
  col2 <- enquo(col2)
  df %>%  
    select(!!col1, !!col2) %>% 
    unnest_tokens(word, !!col2) 
}

myFn(df, id, descr)
#> # A tibble: 4 x 2
#>      id    word
#>   <dbl>   <chr>
#> 1     1   hello
#> 2     1     bug
#> 3     2 goodbye
#> 4     2     bug
```

Thanks for using our package; let me know if you run into any problems with implementing tidyeval solutions with it.

**Comment by juliasilge** [comment]
I'm reopening this as a reminder to myself to update the rest of tidytext's functions.

**Comment by dan-reznik** [comment]
thank you julia! looking fwd to using it

dan
