### ISSUE TITLE
cast_* functions are dropping documents

### ISSUE THREAD

**Issue by realrbird** [juliasilge/tidytext#78]
I have original data with n number of documents and a DocumentTermMatrix with n number of documents as well named my_dtm.  I need to turn my_dtm into a quanteda DFM so I do this 

my_dfm <- tidytext::tidy(my_dtm) %>%
    cast_dfm(document, term, count)

the the result only gives me n-1 documents instead of n documents.  I assume any documents with no words are dropped. But this causes problems later when I try and column bind the LDA probabilities to my original data since they don't have the same nrow() value.  Is there a way to cast and make sure that the cast_* functions return the same number of documents?

**Comment by patperry** [comment]
I've also run into this issue. The problem is that in its current implementation, a tidy word count data frame is a lossy format. It drops empty texts.

In corpus ( http://ptrckprry.com/r-corpus/ ) I got around this issue in `corpus::term_frame` by having a "text" column, a factor with levels equal to the  names of the unique documents. Even if a document has no tokens (and thus no rows in the data frame), you will know about its existence.

**Comment by realrbird** [comment]
Thank you for the response, I suspected it was dropping empty texts, so thanks for the confirmation.  Can the Corpus package cast to and from DocumentTermMatrix and DFM objects, I don't see that in the docs? if not I would have to use tidytext for this and I think this is where I am losing data.

**Comment by patperry** [comment]
*corpus* doesn't have that functionality yet, but it's coming. Regardless, it probably makes the most sense to just go directly from DocumentTermMatrix to DFM object. Here's an example:

```r
library("quanteda")
library("tm")
data("crude")

x_tm <- tm::DocumentTermMatrix(crude)
x_Matrix <- Matrix::sparseMatrix(x_tm$i, x_tm$j, x = x_tm$v,
                                 dims = dim(x_tm), dimnames = dimnames(x_tm))
x_quanteda <- methods::new("dfmSparse", x_Matrix)
```

**Comment by realrbird** [comment]
That is perfect, I was trying to convert to data.frame and then to dfm but data was too large, converting to sparseMatrix and then to dfm should work perfectly. Thank you very much for the help.
