### ISSUE TITLE
Add a few more tests?

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/tidytext#8]
I added `codecov` today and things look pretty decent. If we wanted to get a bit higher on test coverage eventually, it would be good to write some more tests for `sparse_casters.R` and some (one?) for `dictionary_tidiers.R`.

Here's the link showing details:
https://codecov.io/gh/juliasilge/tidytext

**Comment by dgrtwo** [comment]
I think I've added test cases for most of the less covered cases.

Unfortunately we're running into the same issue on Travis that causes Gutenbergr to be blocked :( I think it's possible Project Gutenberg is blocking Travis's IPs even on these generally allowed URLs. But I'll look into it for both packages!

**Comment by juliasilge** [comment]
@dgrtwo Do you know why codecov thinks there are no tests for lda_tidiers? If you click on the link:
https://codecov.io/gh/juliasilge/tidytext
and click through to the tree structure thingie, it says that lda_tidiers has 0 coverage. But there are tests for those functions?! Do you know what is going on here? :weary:

**Comment by juliasilge** [comment]
I was looking at the codecov thing again today, and I think I understand why codecov was not "seeing" all of the tests. In the tests for the LDA tidiers, the assignment for the LDA object is outside of the tests themselves so codecov could not tell that the calls to `tidy`, etc were actually calls to `tidy.LDA` and so forth. In commit 4e3c2e126c69d46c84896c9552f703ef0c050123 I edited the tests in test-lda-tidiers.R to specifically call `tidy.LDA` and similar instead of their aliases. The code coverage is now up to 90% because now codecov knows that is what is being called.

I think we have three options here.
1. Leave the test as it was and have codecov show a lower coverage than we actually have, by a lot.
2. Call `tidy.LDA`, `augment.LDA` in the tests, as I have it now.
3. Repeat the assignment of `lda <- LDA(ap, ...` and such within each `test_that` statement, copy/paste style.

@dgrtwo, which do you think is the best option? I lean toward option 2, I think?
