### ISSUE TITLE
Off topics

### ISSUE THREAD

**Issue by TheOne000** [juliasilge/tidytext#83]
Dear  Julia
      First, thank you very much for your comments and your help on the stackoverflow. Those comments mean the most to me. I have recently finished my dissertation and I have benefited greatly from the discussion with you on the site.
    I am writing to you to thank you for everything and I have acknowledged you on my dissertation. I cannot find your personal email, so, I ended up expressing my gratitude here. (It may be inappropriate, but it is the best way that I am able to do.)
With great regards
Sapphasak :)

**Comment by juliasilge** [comment]
Oh, thank you SO MUCH! 🙏 

I am so glad to hear that your dissertation is finished, and it means so much that you have found practical help in your work. I wish you all the best as you move forward!
