### ISSUE TITLE
cast_dfm is transposed

### ISSUE THREAD

**Issue by dellis83** [juliasilge/tidytext#90]
The values from cast_dfm appear to be transposed.  I tried with my own data set manually building a dfm with quantenda, and the results were transposed from what I came up with tidytext. 

Also, from the text mining with R example:
cast_dtm output
## <<DocumentTermMatrix (documents: 2246, terms: 10473)>>
cast_dfm output 
## Document-feature matrix of: 10,473 documents, 2,246 features (98.7% sparse).

I am very new to this package and R in general, so I apologize if this is just user error. I love this package though ,thanks for your help!

**Comment by juliasilge** [comment]
Thanks so much for the note here! 🙌 You are exactly right. I have updated this on [our book's GitHub site](https://github.com/dgrtwo/tidy-text-mining/commit/36370eeb3b519dfc57d9d9f2510a21c11ecb3e23) and submitted this to the [errata on the O'Reilly site](http://www.oreilly.com/catalog/errata.csp?isbn=0636920067153).

**Comment by dellis83** [comment]
Hi Julia, if I recall correctly, the actual result was transposed too, not just the text in the book. I had to manually transpose it to use it as a document feature matrix. Thanks for looking at it!
