### ISSUE TITLE
No indefinite articles in mobypos.i.zip

### ISSUE THREAD

**Issue by twedl** [juliasilge/tidytext#92]
### Where are the indefinite articles in Moby?
"a" and "an" are listed as definite articles (among other things) in `parts_of_speech`. It looks like the input data does the same:
```
# try to filter for codes with capital "I" for indefinite article, 
# or the things we know are indefinite articles, "a" and "an"
readr::read_delim("data-raw/mobyposi.i.zip", delim = "\xd7",
                  col_names = c("word", "code")) %>% 
  filter(grepl("I", code) | word %in% c("a", "an"))
Multiple files in zip: reading 'mobyposi.i'
Parsed with column specification:
cols(
  word = col_character(),
  code = col_character()
)
|==========================================================| 100%    2 MB
# A tibble: 2 x 2
   word  code
  <chr> <chr>
1    an    DC
2     a  DNVP
```
I tried to find another copy of [mobypos](https://ia802306.us.archive.org/23/items/mobypartofspeech03203gut/mobypos.txt) online and found the same thing.  It seems like such an obvious problem that I must be missing something...:thinking:

Q: is there a better pos dataset, or should I be fixing problems as I find them?

Merry Christmas and Happy Holidays etc. 🎄 🎁

**Comment by twedl** [comment]
I found a few other POS datasets, it seems they all use "Article" instead of "Definite Article" and "Indefinite Article". 

The set [SUBTLEXus](https://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexus/overview.htm) (found via [Language Goldmine](http://languagegoldmine.com/)) lists "a" under "Article" (along with "an", "every" and "the"), but also ranks all its POS choices based on the frequency of each POS in that entry. 

POS tagging is done by [CLAWS](http://ucrel.lancs.ac.uk/claws/) on the British National Corpus.

**Comment by twedl** [comment]
If one would like to use the SUBTLEXus POS dataset:

Go download the txt [.zip file](http://crr.ugent.be/papers/SUBTLEX-US_frequency_list_with_PoS_information_final_text_version.zip). I'm not sure what the license / citation requirements are, but the surrounding info is [here](https://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexus/overview.htm).

Then similar processing as the `mobyposi.i.zip` file gives a similar dataset (with an extra column to help you decide which POS you want to use). See above link for more documentation. There are other files for other languages (including British english, I think). They're based on subtitles from US films and tv shows.

```
parts_of_speech <- readr::read_tsv("data-raw/SUBTLEX-US_frequency_list_with_PoS_information_final_text_version.zip") %>% 
  mutate(code = All_PoS_SUBTLEX %>% stringr::str_split(pattern = "\\."),
         freq = All_freqs_SUBTLEX %>% stringr::str_split(pattern = "\\.")) %>% 
  unnest() %>%
  select(word = Word, code, freq) %>% 
  filter(!is.na(as.numeric(freq)))
parts_of_speech
# A tibble: 102,859 x 3
    word        code   freq
   <chr>       <chr>  <chr>
 1     a     Article 993445
 2     a      Adverb  33186
 3     a      Letter   6441
 4     a          To    744
 5     a        Noun    257
 6     a Preposition     52
 7     a   Adjective      5
 8    aa        Name     79
 9    aa        Noun      7
10   aaa        Name     20
# ... with 102,849 more rows
```

**Comment by juliasilge** [comment]
Thanks so much for your interest in this project! 🙌 We definitely do not want to change anything in the source data set (i.e. "fix" definite to indefinite article) as that is how they were published (the linguists who build them sometimes mean certain things by certain definitions and I am still learning all this from the linguistics side). I looked into other POS data sets at one point and I also found that they seem to have "article" as a category in them, not divided out. 

I'm open to expanding the part of speech lexicons we have in the package, if you are interested in submitting a PR. We should model this after the sentiment lexicons and have a data frame with columns `word`, `pos`, `lexicon`, and I guess `freq` that can be `NA` for the Moby lexicon.

If you are interested in a more complex model for POS tagging, check out the [cleanNLP](https://github.com/statsmaths/cleanNLP) package.

**Comment by twedl** [comment]
Ok, great 🙃! I'm double-checking the license of SUBTLEXus with the authors; if it's licensed only for academic / non-commercial uses, then we wouldn't be able to include it since tidytext has an MIT license---which allows someone "sell copies of the Software" (and the data inside), I think.

cleanNLP looks really cool. I'll get into it when I want to get my hands dirty.

**Comment by twedl** [comment]
The author responded (after a holiday break), saying it's intended for non-commercial use only, so I think the safer option would be just to link to that data somewhere in the docs (or hope someone will find this issue and the links to different dataset options). 😕 Not ideal, but it solves my problem, at least.

**Comment by juliasilge** [comment]
Thanks so much, @tweed1e! I added a link and reference to the `Details` section of the POS doc.
