### ISSUE TITLE
A link to the book?

### ISSUE THREAD

**Issue by privefl** [juliasilge/tidytext#93]
I must be blind but I can't find any link to your book from this GitHub repo :-(

Could you add more links to go directly to the book from this repo? Thanks

**Comment by sigurdurthorjonsson** [comment]
A fixed issue was referred to a few days ago in this thread like so:

Thanks so much for the note here! 🙌 You are exactly right. I have updated
this on our book's GitHub site
<https://github.com/dgrtwo/tidy-text-mining/commit/36370eeb3b519dfc57d9d9f2510a21c11ecb3e23>
and
submitted this to the errata on the O'Reilly site
<http://www.oreilly.com/catalog/errata.csp?isbn=0636920067153>.

but the github-root of the book is:

https://github.com/dgrtwo/tidy-text-mining

and it is renrdered at:

https://www.tidytextmining.com/


HTH,

Siggi

**Comment by privefl** [comment]
Could you add links in the README of this repo so that the book is visible from this repo?

**Comment by juliasilge** [comment]
That's a great idea; thanks! 🙌
