### ISSUE TITLE
Error: Result 16 is not a length 1 atomic vector

### ISSUE THREAD

**Issue by randomgambit** [juliasilge/tidytext#97]
Hello,

Thanks again for this wonderful package. I am getting this rather cryptic error when I try to `tidy` a corpus. Running `str(corpus)` shows some reasonable output, but

`text_df <- tidy(corpus, collapse = "\n")` or
`text_df <- tidy(corpus)`

both return 

```
> text_df <- tidy(corpus, collapse = "\n")
Error: Result 16 is not a length 1 atomic vector
```

Is this a bug? This exact code used to work in the past.
Thanks!

**Comment by randomgambit** [comment]
@juliasilge @jimhester it appears in the `meta` tags I have a couple `mytag  : character(0)`.  
Is that the source of the issue here? can I fix that?

Thanks!!

**Comment by juliasilge** [comment]
Hello there, @randomgambit! Thanks for reporting a problem. A reproducible example will make it possible to diagnose what's going wrong. Is this a tm `Corpus` or a quanteda `corpus`? Can you make a small example corpus object, probably that has the empty character bits that may be the problem? Then I can find the part of the code that is breaking.

**Comment by juliasilge** [comment]
Hello there, @randomgambit! Let me know if/when you are able to put together a reproducible example to help diagnose your problem. I'm going to close this issue for now. Good luck!
